### ISSUE TITLE
ActiveAndroid with Parceler dependency issue

### ISSUE THREAD

**Issue by Dwite** [johncarl81/parceler#103]
I'm getting
```
java.lang.NoClassDefFoundError: org.parceler.transfuse.AnnotationProcessorBase
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:309)
            at com.activeandroid.ModelInfo.scanForModelClasses(ModelInfo.java:187)
            at com.activeandroid.ModelInfo.scanForModel(ModelInfo.java:152)
            at com.activeandroid.ModelInfo.<init>(ModelInfo.java:63)
            at com.activeandroid.Cache.initialize(Cache.java:66)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:30)
            at asdasd.ru.activeandroidtest.Aasdasda.onCreate(Aasdasda.java:15)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
            at android.app.ActivityThread.access$1500(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
when I'm trying to use ActiveAndroid and Parceler together.

Gradle :
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.michaelpardo:activeandroid:3.1.0-SNAPSHOT'
    compile 'com.android.support:multidex:1.0.0'

    compile 'org.parceler:parceler:1.0.0'
    provided 'org.parceler:parceler:1.0.0'
}
```

ApplicationClass
```
public class Aasdasda extends MultiDexApplication {

    @Override
    public void onCreate() {
        super.onCreate();
        ActiveAndroid.initialize(this);
    }
}
```

Proguard
```
# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /Users/valery.kuznetsov/Library/Android/sdk/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

-keep class !android.support.v7.internal.view.menu.**,** {*;}
-dontwarn
-ignorewarnings
-dontshrink
-dontwarn com.squareup.okhttp.**

-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
    **[] $VALUES;
    public *;
}
-keep class com.marshalchen.ultimaterecyclerview.** { *; }
-keep public class * extends class com.marshalchen.ultimaterecyclerview
-keepclassmembers class com.marshalchen.ultimaterecyclerview.** { *; }

#ActiveAndroid
-keep class com.activeandroid.** { *; }
-keep public class my.app.database.** { *; }
-keepattributes Column
-keepattributes Table
-keepattributes *Annotation*

## transfuse
-keep class org.androidtransfuse.Transfuse$** { *; }
 -dontwarn org.androidtransfuse.**
 -dontwarn com.sun.**
 -dontwarn java_.**
 -dontwarn javax_.**

 ## optimize
 -optimizations !code/simplification/arithmetic,!code/simplification/cast,!field/*,!class/merging/*
 -optimizationpasses 5
 -allowaccessmodification
 -dontpreverify

 ## standard
 -dontusemixedcaseclassnames
 -dontskipnonpubliclibraryclasses
 -verbose
 -keepattributes *Annotation*
 -keep public class com.google.vending.licensing.ILicensingService
 -keep public class com.android.vending.licensing.ILicensingService
 -keepclasseswithmembernames class * { native <methods>; }
 -keepclassmembers public class * extends android.view.View { void set*(***); *** get*(); }
 -keepclassmembers class * extends android.app.Activity { public void *(android.view.View); }
 -keepclassmembers enum * { public static **[] values(); public static ** valueOf(java.lang.String); }
 -keep class * implements android.os.Parcelable { public static final android.os.Parcelable$Creator *; }
 -keepclassmembers class **.R$* { public static <fields>; }
 -dontwarn android.support.**

 -keep class * implements android.os.Parcelable {
   public static final android.os.Parcelable$Creator *;
 }

 -keep class org.parceler.Parceler$$Parcels
```

**Comment by johncarl81** [comment]
It's probably your dependencies.  You've declared Parceler twice, where you need the api as well:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.michaelpardo:activeandroid:3.1.0-SNAPSHOT'
    compile 'com.android.support:multidex:1.0.0'

    compile 'org.parceler:parceler-api:1.0.0'
    provided 'org.parceler:parceler:1.0.0'
}
```

Let me know if it continues to fail.

**Comment by Dwite** [comment]
I'm not sure what exactly did you mean, you want me to leave
```
    compile 'org.parceler:parceler-api:1.0.0'
```
or
```
    provided 'org.parceler:parceler:1.0.0'
```

in my build gradle?

**Comment by johncarl81** [comment]
Change `"compile 'org.parceler:parceler:1.0.0'`" to "`compile 'org.parceler:parceler-api:1.0.0'`".

Leave "`provided 'org.parceler:parceler:1.0.0'`" as is.
https://github.com/johncarl81/parceler#getting-parceler

**Comment by Dwite** [comment]
Yeah, it worked perfectly, thank you so much!

**Comment by johncarl81** [comment]
Fantastic :beers:

**Comment by Dwite** [comment]
Well, not something gone wrong :(

I'm getting 
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/thirdparty/publicsuffix/PublicSuffixPatterns;
            at org.parceler.Parceler$$Parcels.<init>(Parceler$$Parcels.java:25)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.Class.newInstance(Class.java:1606)
            at org.parceler.Parcels$ParcelCodeRepository.loadRepository(Parcels.java:238)
            at org.parceler.Parcels$ParcelCodeRepository.<init>(Parcels.java:190)
            at org.parceler.Parcels.<clinit>(Parcels.java:37)
            at ru.urujdas.fragments.NewsFragment.onItemClick(NewsFragment.java:91)
```

When I'm trying to 
```
Parcels.wrap(mNewsAdapter.getItem(position)
```
Object that i'm parsing :
```
public class News {

    public Author mAuthor;
    public String mDate;
    public String mImagePreviewUrl;
    public String mDescription;

    public News() {}

    public News(Author author, String date, String imagePreviewUrl, String description) {
        mAuthor = author;
        mDate = date;
        mImagePreviewUrl = imagePreviewUrl;
        mDescription = description;
    }

    public Author getAuthor() {
        return mAuthor;
    }

    public String getDate() {
        return mDate;
    }

    public String getImagePreviewUrl() {
        return mImagePreviewUrl;
    }

    public String getDescription() {
        return mDescription;
    }
}
```
My application class
```
@ParcelClasses({@ParcelClass(News.class), @ParcelClass(Author.class), @ParcelClass(PublicSuffixPatterns.class)})
public class UrujdasApplication extends MultiDexApplication
```
