### ISSUE TITLE
ParcelerRuntimeException when trying to start an activity with ACTION_SEND intent

### ISSUE THREAD

**Issue by LaurieScheepers** [johncarl81/parceler#106]
Hi

I'm trying to start an activity with ACTION_SEND as the intent's action. This activity is started from a fragment that has a Parcelable object (of type Message class) as a member variable:

```java
Intent sendIntent = new Intent();
sendIntent.setAction(Intent.ACTION_SEND);
sendIntent.putExtra(Intent.EXTRA_TEXT, baseUrl + "/" + message.getMessageId());
sendIntent.setType("text/plain");
getActivity().startActivity(Intent.createChooser(sendIntent, "Share message"));
```

where `message` is the Parcelable object (which is also a Realm object - you'll remember I posted an issue here about Parceler and Realm objects some time ago). However, after the chooser is created, the app crashes with the following exception (full stacktrace included)

```
org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for io.realm.MessageRealmProxy, verify that your class is configured properly and that the Parcelable class io.realm.MessageRealmProxy$$Parcelable is generated by Parceler.
            at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:201)
            at org.parceler.Parcels.wrap(Parcels.java:85)
            at org.parceler.Parcels.wrap(Parcels.java:69)
            at org.parceler.NonParcelRepository$ListParcelable$1.itemToParcel(NonParcelRepository.java:280)
            at org.parceler.converter.CollectionParcelConverter.toParcel(CollectionParcelConverter.java:38)
            at org.parceler.converter.CollectionParcelConverter.toParcel(CollectionParcelConverter.java:27)
            at org.parceler.NonParcelRepository$ConverterParcelable.writeToParcel(NonParcelRepository.java:1222)
            at org.parceler.NonParcelRepository$ListParcelable.writeToParcel(NonParcelRepository.java:269)
            at android.os.Parcel.writeParcelable(Parcel.java:1357)
            at android.os.Parcel.writeValue(Parcel.java:1262)
            at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
            at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
            at android.os.Bundle.writeToParcel(Bundle.java:1096)
            at android.os.Parcel.writeBundle(Parcel.java:663)
            at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:137)
            at android.os.Parcel.writeTypedArray(Parcel.java:1191)
            at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:384)
            at android.os.Parcel.writeParcelable(Parcel.java:1357)
            at android.os.Parcel.writeValue(Parcel.java:1262)
            at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
            at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
            at android.os.Bundle.writeToParcel(Bundle.java:1096)
            at android.os.Parcel.writeBundle(Parcel.java:663)
            at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2901)
            at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3290)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

I've tried putting a different parameter for the intent (i.e. no reference to the Message class) but still I get the same crash. Starting an activity with action ACTION_VIEW works fine.

Is there anything I'm doing wrong? I understand that one shouldn't pass Parcelable objects to other apps (because they won't be able to know how to deserialize it) but in this case I'm just passing a String. Actually passing anything to that intent causes the crash.

I can verify that the Message parcelable object is wrapped and unwrapped correctly as I refer to it all over the place in the fragment without any issues.

**Comment by johncarl81** [comment]
Hmm, that's an interesting one... is Realm creating a proxy for your class (`MessageRealmProxy`?).  If that's the case you may have to write a converter to avoid the proxy... can you share the code around your other beans, particularly `Message`?

**Comment by LaurieScheepers** [comment]
Can I rather mail you the code?

**Comment by johncarl81** [comment]
Sure, or you can share on github.

**Comment by LaurieScheepers** [comment]
Cool, mailed it to you

**Comment by johncarl81** [comment]
Closing.  Solved by the implmentations parameter (see https://github.com/realm/realm-java/issues/1236)
