### ISSUE TITLE
Using JodaTime.Datetime - TransfuseAdapterException - Proxy not initialized prior to use

### ISSUE THREAD

**Issue by akohout** [johncarl81/parceler#114]
I implemented your library for my models, but it does not seem to work with Custom (De-)Serialization using the ParcelConvert class.

I already found this issue https://github.com/johncarl81/parceler/issues/51 where you already provided an example of how to write and read a DateTime. I just copy & pasted it, so my code looks like below:

```Java
public class DateTimeParcelConverter implements ParcelConverter<DateTime> {

	@Override
	public void toParcel(final DateTime input, final Parcel parcel) {
		if (input == null) {
			parcel.writeInt(-1);
		} else {
			parcel.writeInt(1);
			parcel.writeLong(input.getMillis());
		}
	}

	@Override
	public DateTime fromParcel(final Parcel parcel) {
		int nullCheck = parcel.readInt();
		DateTime result;
		if (nullCheck < 0) {
			result = new DateTime();
		} else {
			result = new DateTime(parcel.readLong());
		}
		return result;
	}
}

@Parcel
public class Recommendation {
   ...

   @ParcelPropertyConverter(DateTimeParcelConverter.class)
    public DateTime createdAt;
}
```

When I remove the ParcelPropertyConverter annotation and replace it with the Transient annotation, the compilation works - that's why the issue must be with the converter.

By the way, this is the stack trace (if that's somehow useful):

```
Exception in thread "pool-60-thread-3" org.parceler.transfuse.TransfuseAdapterException: Proxy not initialized prior to use
error: Parceler: Code generation did not complete successfully.  For more details add the compiler argument -AparcelerStacktrace
	at org.parceler.transfuse.adapter.ASTTypeVirtualProxy.getProxy(ASTTypeVirtualProxy.java:45)
	at org.parceler.transfuse.adapter.ASTTypeVirtualProxy.inheritsFrom(ASTTypeVirtualProxy.java:95)
	at org.parceler.transfuse.gen.invocationBuilder.TypeInvocationHelper.coerceType(TypeInvocationHelper.java:60)
	at org.parceler.transfuse.gen.invocationBuilder.PublicInvocationBuilder.buildFieldSet(PublicInvocationBuilder.java:76)
	at org.parceler.transfuse.gen.InvocationBuilder.buildFieldSet(InvocationBuilder.java:71)
	at org.parceler.internal.ReadReferenceVisitor.visit(ReadReferenceVisitor.java:41)
	at org.parceler.internal.ReadReferenceVisitor.visit(ReadReferenceVisitor.java:28)
	at org.parceler.internal.FieldReference.accept(FieldReference.java:41)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcel(ParcelableGenerator.java:226)
	at org.parceler.internal.ParcelableGenerator.buildParcelRead(ParcelableGenerator.java:171)
	at org.parceler.internal.generator.ParcelReadWriteGenerator.generateReader(ParcelReadWriteGenerator.java:66)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcelExpression(ParcelableGenerator.java:286)
	at org.parceler.internal.ParcelableGenerator.generateParcelable(ParcelableGenerator.java:105)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:52)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:32)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
	at org.parceler.transfuse.transaction.Transaction.run(Transaction.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by johncarl81** [comment]
Well, that shouldn't be happening... are you using Parceler version 1.0.1?

Something to try, with 1.0.1 you need to annotate any methods with `@ParcelPropertyConverter` also with `@ParcelProperty`.  You can also use the `NullableParcelConverter` to avoid some boilerplate. In your case this would look like:
```java
public class DateTimeParcelConverter extends NullableParcelConverter<DateTime> {

    @Override
    public void nullSafeToParcel(final DateTime input, final Parcel parcel) {
        parcel.writeLong(input.getMillis());
    }

    @Override
    public DateTime nullSafeFromParcel(final Parcel parcel) {
        return new DateTime(parcel.readLong());
    }
}

@Parcel
public class Recommendation {
    @ParcelProperty("createdAt")
    @ParcelPropertyConverter(DateTimeParcelConverter.class)
    public DateTime createdAt;
}
```

In the upcoming 1.0.2 release we removed the requirement that `@ParcelPropertyConverter` requires `@ParcelProperty`.

**Comment by johncarl81** [comment]
Running this myself I encountered the same error... this is happening because Parceler (and the Transfuse core behind the scenes) is trying to find the class `org.joda.convert.ToString`, but this class doesn't exist.  This fix will be included in 1.0.2: https://github.com/johncarl81/transfuse/issues/153 .   Sounds like I need to make a release ASAP.

**Comment by akohout** [comment]
Ah ok, thanks for the information. If the 1.0.2 release still takes some time, you could just update the documentation with this piece of information.

**Comment by johncarl81** [comment]
I'll make a release this evening.

**Comment by johncarl81** [comment]
[1.0.2 released](https://twitter.com/attransfuse/status/623293642870927360)

**Comment by akohout** [comment]
Great job, thanks for the update
