### ISSUE TITLE
Unable to parcel. 

### ISSUE THREAD

**Issue by rakesh-3607** [johncarl81/parceler#115]
My Response class is {

String a;
string b;
List<C> cList;
}

Unable to parcel List with custom Type.

Would you please help with resolving this error ?
..............................................................................................
Exception in thread "pool-40-thread-1" org.parceler.ParcelerRuntimeException: Unable to find appropriate Parcel method to write com.pyrexx.pyrexxapp.rest.model.HouseListServiceApiResponse.EwbSearchResult
	at org.parceler.internal.Generators.getGenerator(Generators.java:49)
	at org.parceler.internal.generator.ListReadWriteGenerator.generateReader(ListReadWriteGenerator.java:82)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcelExpression(ParcelableGenerator.java:282)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcel(ParcelableGenerator.java:234)
	at org.parceler.internal.ParcelableGenerator.buildParcelRead(ParcelableGenerator.java:166)

 FAILED

	at org.parceler.internal.ParcelableGenerator.generateParcelable(ParcelableGenerator.java:100)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:54)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:34)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
	at org.parceler.transfuse.transaction.Transaction.run(Transaction.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJava'.
> org.parceler.transfuse.TransfuseAnalysisException: @Parcel code generation did not complete successfully.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by johncarl81** [comment]
That's strange.. that should be a validation error instead of a runtime exception.  What version of Parceler are you using?  If it's not 1.0.2, please upgrade.

Is `EwbSearchResult` the inner class you were referring to?  It looks like you need to annotate it with `@Parcel`.  Can you share some more of your code?
