### ISSUE TITLE
Parceler and FragmentManagerState

### ISSUE THREAD

**Issue by crebstock** [johncarl81/parceler#124]
I'm getting a "Unable to find generated Parcelable class" error when my Fragment goes to the background.  It attempts to save its state and crashes.  The Parceler object passes through the arguments and is wrapped and unwrapped just fine.  Has anyone else experienced this issue?  I'm hoping its just something silly that I'm doing.

I've attached a project below which shows the behavior, and the error is pasted below that.  Here is the code from the fragment:
   
    public static MainFragment newInstance(ArrayList<PTestObject> offers) {
        MainFragment fragment = new MainFragment();
        Bundle arguments = new Bundle();
        arguments.putParcelable(TEST_PARCEL_KEY,
                Parcels.wrap(offers));
        fragment.setArguments(arguments);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ArrayList<PTestObject> offers = Parcels.unwrap(getArguments().getParcelable(TEST_PARCEL_KEY));
        Log.d(TAG, "Test: " + offers.size());
    }

Example Project:
https://drive.google.com/file/d/0B9_IneRavAf2UEtwTnUyWkFJQU0/view?usp=sharing

Error output:
09-04 14:53:24.187  26827-26827/com.test.android.app.parcelerfragmenttest E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.test.android.app.parcelerfragmenttest, PID: 26827
    org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for com.test.android.app.parcelerfragmenttest.PTestObject, verify that your class is configured properly and that the Parcelable class com.test.android.app.parcelerfragmenttest.PTestObject$$Parcelable is generated by Parceler.
            at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:201)
            at org.parceler.Parcels.wrap(Parcels.java:85)
            at org.parceler.Parcels.wrap(Parcels.java:69)
            at org.parceler.NonParcelRepository$ListParcelable$1.itemToParcel(NonParcelRepository.java:280)
            at org.parceler.converter.CollectionParcelConverter.toParcel(CollectionParcelConverter.java:38)
            at org.parceler.converter.CollectionParcelConverter.toParcel(CollectionParcelConverter.java:27)
            at org.parceler.NonParcelRepository$ConverterParcelable.writeToParcel(NonParcelRepository.java:1222)
            at org.parceler.NonParcelRepository$ListParcelable.writeToParcel(NonParcelRepository.java:269)
            at android.os.Parcel.writeParcelable(Parcel.java:1416)
            at android.os.Parcel.writeValue(Parcel.java:1322)
            at android.os.Parcel.writeArrayMapInternal(Parcel.java:665)
            at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
            at android.os.Bundle.writeToParcel(Bundle.java:1079)
            at android.os.Parcel.writeBundle(Parcel.java:690)
            at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:137)
            at android.os.Parcel.writeTypedArray(Parcel.java:1233)
            at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:384)
            at android.os.Parcel.writeParcelable(Parcel.java:1416)
            at android.os.Parcel.writeValue(Parcel.java:1322)
            at android.os.Parcel.writeArrayMapInternal(Parcel.java:665)
            at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
            at android.os.Bundle.writeToParcel(Bundle.java:1079)
            at android.os.Parcel.writeBundle(Parcel.java:690)
            at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3152)
            at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3417)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by johncarl81** [comment]
The issue is in your build file where you've declated the following:
```groovy
    compile 'org.parceler:parceler-api:1.0.3'
    provided 'org.parceler:parceler-api:1.0.3'
```
I'd recommend using the [apt plugin](https://bitbucket.org/hvisser/android-apt) and the following depdency scope instead (and properly including the parceler annotation processor):
```groovy
    compile 'org.parceler:parceler-api:1.0.3'
    apt 'org.parceler:parceler:1.0.3'
```

See http://parceler.org/#getting_parceler

**Comment by crebstock** [comment]
Sure enough, that fixed it.  Thanks for pointing out the miss on my part!
