### ISSUE TITLE
Crash when leaving a fragment that contains a Parceler unwrapped object

### ISSUE THREAD

**Issue by ddmmcjmm** [johncarl81/parceler#126]
First of all, I have also posted this question here on [StackOverflow](http://stackoverflow.com/questions/32560737/crash-when-trying-to-leave-a-fragment-that-contains-a-parceler-unwrapped-object).

I have an abstract class that is annotated with `@Parcel`. It has a concrete subclass `MyMovie` but it is not annotated.

I can successfully create a fragment by passing `MyMovie` to the args bundle. All is fine, for both wrapping `MyMovie` and unwrapping the parcelable.

Problem occurs when I try to leave the fragment, for example, by pressing home button. Here is the stack trace:

    09-14 16:39:33.688  29389-29389/com.example.myapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.myapp, PID: 29389
    org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for com.example.myapp.MyMovie, verify that your class is configured properly and that the Parcelable class com.example.myapp.MyMovie$$Parcelable is generated by Parceler.
            at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:201)
            at org.parceler.Parcels.wrap(Parcels.java:85)
            at org.parceler.Parcels.wrap(Parcels.java:69)
            at org.parceler.NonParcelRepository$ListParcelable$1.itemToParcel(NonParcelRepository.java:280)
            at org.parceler.converter.CollectionParcelConverter.toParcel(CollectionParcelConverter.java:38)
            at org.parceler.converter.CollectionParcelConverter.toParcel(CollectionParcelConverter.java:27)
            at org.parceler.NonParcelRepository$ConverterParcelable.writeToParcel(NonParcelRepository.java:1222)
            at org.parceler.NonParcelRepository$ListParcelable.writeToParcel(NonParcelRepository.java:269)
            at android.os.Parcel.writeParcelable(Parcel.java:1285)
            at android.os.Parcel.writeValue(Parcel.java:1204)
            at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
            at android.os.Bundle.writeToParcel(Bundle.java:1692)
            at android.os.Parcel.writeBundle(Parcel.java:636)
            at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:137)
            at android.os.Parcel.writeTypedArray(Parcel.java:1133)
            at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:384)
            at android.os.Parcel.writeParcelable(Parcel.java:1285)
            at android.os.Parcel.writeValue(Parcel.java:1204)
            at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
            at android.os.Bundle.writeToParcel(Bundle.java:1692)
            at android.os.Parcel.writeBundle(Parcel.java:636)
            at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:138)
            at android.os.Parcel.writeTypedArray(Parcel.java:1133)
            at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:384)
            at android.os.Parcel.writeParcelable(Parcel.java:1285)
            at android.os.Parcel.writeValue(Parcel.java:1204)
            at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
            at android.os.Bundle.writeToParcel(Bundle.java:1692)
            at android.os.Parcel.writeBundle(Parcel.java:636)
            at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2526)
            at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3112)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
            at dalvik.system.NativeStart.main(Native Method)

This is how I include `Parceler` in my app-level `build.gradle`:

    compile 'org.parceler:parceler-api:1.0.3'

Thanks for helping.

**Comment by johncarl81** [comment]
Have you included the parceler annotation processor?:
```
apt 'org.parceler:parceler:1.0.3'
```
parceler.org#getting_parceler

**Comment by johncarl81** [comment]
From the [looks of it](http://stackoverflow.com/questions/32560737/crash-when-trying-to-leave-a-fragment-that-contains-a-parceler-unwrapped-object), this issue is solved.
