### ISSUE TITLE
ParcelPropertyConverter for CharSequence doesn't seem to work.

### ISSUE THREAD

**Issue by liangricha** [johncarl81/parceler#137]
Hi!

I made a `ParcelPropertyConverter` for `CharSequence`, which looks like:

    public static class CharSequenceParcelConverter implements ParcelConverter<CharSequence> {
            @Override
            public void toParcel(CharSequence charSequence, Parcel parcel) {
                TextUtils.writeToParcel(charSequence, parcel, 0);
            }

            @Override
            public CharSequence fromParcel(Parcel parcel) {
                return TextUtils.CHAR_SEQUENCE_CREATOR.createFromParcel(parcel);
            }
    }

I have annotated my `CharSequence` field with:

`@ParcelPropertyConverter(CharSequenceParcelConverter.class)`

But get the following build error when attempting to compile:

```
xception in thread "pool-83-thread-1" org.parceler.ParcelerRuntimeException: Unable to find appropriate Parcel method to write java.lang.CharSequence
	at org.parceler.internal.Generators.getGenerator(Generators.java:58)
	at org.parceler.internal.generator.ArrayReadWriteGenerator.generateReader(ArrayReadWriteGenerator.java:79)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcelExpression(ParcelableGenerator.java:286)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcelExpression(ParcelableGenerator.java:269)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcel(ParcelableGenerator.java:230)
	at org.parceler.internal.ParcelableGenerator.buildParcelRead(ParcelableGenerator.java:171)
	at org.parceler.internal.generator.ParcelReadWriteGenerator.generateReader(ParcelReadWriteGenerator.java:66)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcelExpression(ParcelableGenerator.java:286)
	at org.parceler.internal.ParcelableGenerator.generateParcelable(ParcelableGenerator.java:105)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:52)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:32)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
	at org.parceler.transfuse.transaction.Transaction.run(Transaction.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-85-thread-1" org.parceler.ParcelerRuntimeException: Unable to find appropriate Parcel method to write java.lang.CharSequence
	at org.parceler.internal.Generators.getGenerator(Generators.java:58)
	at org.parceler.internal.generator.ArrayReadWriteGenerator.generateReader(ArrayReadWriteGenerator.java:79)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcelExpression(ParcelableGenerator.java:286)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcelExpression(ParcelableGenerator.java:269)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcel(ParcelableGenerator.java:230)
	at org.parceler.internal.ParcelableGenerator.buildParcelRead(ParcelableGenerator.java:171)
	at org.parceler.internal.generator.ParcelReadWriteGenerator.generateReader(ParcelReadWriteGenerator.java:66)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcelExpression(ParcelableGenerator.java:286)
	at org.parceler.internal.ParcelableGenerator.generateParcelable(ParcelableGenerator.java:105)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:52)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:32)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
	at org.parceler.transfuse.transaction.Transaction.run(Transaction.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-87-thread-1" org.parceler.ParcelerRuntimeException: Unable to find appropriate Parcel method to write java.lang.CharSequence
	at org.parceler.internal.Generators.getGenerator(Generators.java:58)
error: Parceler: Code generation did not complete successfully.  For more details add the compiler argument -AparcelerStacktrace
	at org.parceler.internal.generator.ArrayReadWriteGenerator.generateReader(ArrayReadWriteGenerator.java:79)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcelExpression(ParcelableGenerator.java:286)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcelExpression(ParcelableGenerator.java:269)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcel(ParcelableGenerator.java:230)
	at org.parceler.internal.ParcelableGenerator.buildParcelRead(ParcelableGenerator.java:171)
	at org.parceler.internal.generator.ParcelReadWriteGenerator.generateReader(ParcelReadWriteGenerator.java:66)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcelExpression(ParcelableGenerator.java:286)
	at org.parceler.internal.ParcelableGenerator.generateParcelable(ParcelableGenerator.java:105)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:52)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:32)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
	at org.parceler.transfuse.transaction.Transaction.run(Transaction.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
1 error
  ```

Am I not doing something I should do for interfaces? Thanks!

**Comment by johncarl81** [comment]
I was able to use your converter successfuly on my tests.  It's also strange that you are getting a stack trace from this one.  Typically this error will look like the following without a stack trace:
```
[ERROR] /.../ExampleParcel.java:[27,18] Parceler: Unable to find read/write generator for type java.lang.CharSequence for org.parceler.ExampleParcel.blah
```

Can you share more details?  Are you using the default configuration for your `@Parcel` bean?  What version of Parceler are you using?

**Comment by liangricha** [comment]
Hmmm interesting - I tried compiling the project again today and everything seems to be working fine. Might have been something weird going on with my environment?

**Comment by johncarl81** [comment]
Great!
