### ISSUE TITLE
NumberFormatException for Number field

### ISSUE THREAD

**Issue by jimmy0251** [johncarl81/parceler#142]
I'm getting Exception while calling Parcels.wrap for one of my class.
Here's stack track of the Exception : 

java.lang.NumberFormatException: Bad offset/length: offset=0 len=0 in.length=0
                                                                                        at java.math.BigDecimal.<init>(BigDecimal.java:282)
                                                                                        at java.math.BigDecimal.<init>(BigDecimal.java:438)
                                                                                        at com.google.gson.internal.LazilyParsedNumber.writeReplace(LazilyParsedNumber.java:77)
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1595)
                                                                                        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
                                                                                        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
                                                                                        at android.os.Parcel.writeSerializable(Parcel.java:1274)
                                                                                        at com.anantapps.meracrmandroidmaterial.model.Person$$Parcelable.writecom_anantapps_meracrmandroidmaterial_model_CustomField(Person$$Parcelable.java:887)
                                                                                        at com.anantapps.meracrmandroidmaterial.model.Person$$Parcelable.writecom_anantapps_meracrmandroidmaterial_model_Person(Person$$Parcelable.java:635)
                                                                                        at com.anantapps.meracrmandroidmaterial.model.Person$$Parcelable.writeToParcel(Person$$Parcelable.java:42)
                                                                                        at android.os.Parcel.writeParcelable(Parcel.java:1254)
                                                                                        at android.os.Parcel.writeValue(Parcel.java:1173)
                                                                                        at android.os.Parcel.writeMapInternal(Parcel.java:591)
                                                                                        at android.os.Bundle.writeToParcel(Bundle.java:1619)
                                                                                        at android.os.Parcel.writeBundle(Parcel.java:605)
                                                                                        at android.content.Intent.writeToParcel(Intent.java:6470)
                                                                                        at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:1741)
                                                                                        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1411)
                                                                                        at android.app.Activity.startActivityForResult(Activity.java:3351)
                                                                                        at android.app.Activity.startActivityForResult(Activity.java:3312)
                                                                                        at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:855)
                                                                                        at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:907)
                                                                                        at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:927)
                                                                                        at com.anantapps.meracrmandroidmaterial.ui.MoreTabFragment.openCustomFormsAndFields(MoreTabFragment.java:184)
                                                                                        at com.anantapps.meracrmandroidmaterial.ui.MoreTabFragment.openActivity(MoreTabFragment.java:145)
                                                                                        at com.anantapps.meracrmandroidmaterial.ui.MoreTabFragment.lambda$initView$132(MoreTabFragment.java:122)
                                                                                        at com.anantapps.meracrmandroidmaterial.ui.MoreTabFragment.access$lambda$0(MoreTabFragment.java)
                                                                                        at com.anantapps.meracrmandroidmaterial.ui.MoreTabFragment$$Lambda$1.onItemClick(Unknown Source)
                                                                                        at android.widget.AdapterView.performItemClick(AdapterView.java:298)
                                                                                        at android.widget.AbsListView.performItemClick(AbsListView.java:1086)
                                                                                        at android.widget.AbsListView$PerformClick.run(AbsListView.java:2855)
                                                                                        at android.widget.AbsListView$1.run(AbsListView.java:3529)
                                                                                        at android.os.Handler.handleCallback(Handler.java:615)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                        at android.os.Looper.loop(Looper.java:137)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                        at dalvik.system.NativeStart.main(Native Method)

Here's line no. 887 of Person$$Parcelable.java 

        parcel$$241 .writeSerializable(customField$$25 .numberValue);

**Comment by johncarl81** [comment]
Hmm, this seems to be a problem with either serialization of `BigDecimal` or GSON handling `BigDecimal`.

I'd suggest mapping a custom converter for `BigDecimal`s and see what happens:

```java
@ParcelClass(value = BigDecimal.class, annotation = @Parcel(converter = BigDecimalConverter.class))
public class BigDecimalConverter extends NullableParcelConverter<BigDecimal> {

    @Override
    public void nullSafeToParcel(BigDecimal input, android.os.Parcel parcel) {
        parcel.writeString(input.toString());
    }

    @Override
    public BigDecimal nullSafeFromParcel(android.os.Parcel parcel) {
        return new BigDecimal(parcel.readString());
    }
}
```

**Comment by jimmy0251** [comment]
I think it's gson library problem. It's generating something like LazyNumber for empty String.
