### ISSUE TITLE
ThreeTen backport and Map<LocalDate, List<CustomClass>> fails to Parcel

### ISSUE THREAD

**Issue by twig** [johncarl81/parceler#151]
On the latest 1.0.4 release, I have a field in my Fragment called "cachedEvents".

    protected Map<LocalDate, List<EventItem>> cachedEvents;

On the save call, I have the following code:

    state.putParcelable("cachedEvents", Parcels.wrap(cachedEvents));

And soon after it throws an exception:

    org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for org.threeten.bp.LocalDate, verify that your class is configured properly and that the Parcelable class org.threeten.bp.LocalDate$$Parcelable is generated by Parceler.
      at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:201)
      at org.parceler.Parcels.wrap(Parcels.java:85)
      at org.parceler.Parcels.wrap(Parcels.java:69)
      at org.parceler.NonParcelRepository$MapParcelable$1.mapKeyToParcel(NonParcelRepository.java:355)
      at org.parceler.converter.MapParcelConverter.toParcel(MapParcelConverter.java:38)
      at org.parceler.converter.MapParcelConverter.toParcel(MapParcelConverter.java:27)
      at org.parceler.NonParcelRepository$ConverterParcelable.writeToParcel(NonParcelRepository.java:1222)
      at org.parceler.NonParcelRepository$MapParcelable.writeToParcel(NonParcelRepository.java:349)
      at android.os.Parcel.writeParcelable(Parcel.java:1285)
      at android.os.Parcel.writeValue(Parcel.java:1204)
      at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
      at android.os.Bundle.writeToParcel(Bundle.java:1692)
      at android.os.Parcel.writeBundle(Parcel.java:636)
      at android.os.Parcel.writeValue(Parcel.java:1201)
      at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
      at android.os.Bundle.writeToParcel(Bundle.java:1692)
      at android.os.Parcel.writeBundle(Parcel.java:636)
      at android.os.Parcel.writeValue(Parcel.java:1201)
      at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
      at android.os.Bundle.writeToParcel(Bundle.java:1692)
      at android.os.Parcel.writeBundle(Parcel.java:636)
      at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:138)
      at android.os.Parcel.writeTypedArray(Parcel.java:1133)
      at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:384)
      at android.os.Parcel.writeParcelable(Parcel.java:1285)
      at android.os.Parcel.writeValue(Parcel.java:1204)
      at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
      at android.os.Bundle.writeToParcel(Bundle.java:1692)
      at android.os.Parcel.writeBundle(Parcel.java:636)
      at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2467)
      at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3084)
      at android.os.Handler.handleCallback(Handler.java:733)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:136)
      at android.app.ActivityThread.main(ActivityThread.java:5001)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:515)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
      at dalvik.system.NativeStart.main(Native Method)

The things I've tried so far are:

* Extending `LocalDate` so I could add `@Parcel` decorator, but it's a final class so cannot be subclassed.
* Using a custom Parceler `LocalDateParceler` with `@ParcelPropertyConverter(LocalDateParceler.class)` but that only works on LocalDate members, not `Map<LocalDate, X>`
* `@ParcelClass(LocalDate.class)` on my `Application` class fails to compile with the following errors.
 * Error:Parceler: No @ParcelConstructor annotated constructor and no default empty bean constructor found.
 * Error:Parceler: Unable to find read/write generator for type short for org.threeten.bp.LocalDate.month
 * Error:Parceler: Unable to find read/write generator for type short for org.threeten.bp.LocalDate.day
* Re-reading the docs over and over.
* Noticed that it's a Serializable, but not quite sure how to make use of that

Clutching at straws now, but hoping you've run into this before and know of some remedy.

Reference: [ThreeTenBP LocalDate src](https://github.com/ThreeTen/threetenbp/blob/master/src/main/java/org/threeten/bp/LocalDate.java)

**Comment by johncarl81** [comment]
You're so close... to register a converter globally you'll need to add it to the `@ParcelClass` on your `Application` class:
```
@ParcelClass(value = LocalDate.class, 
    annotation = @Parcel(converter = LocalDateParceler.class))
```
That should do the trick, as long as your `ParcelConveter` is proper.

**Comment by twig** [comment]
Thank you, that worked beautifully!

Oh @johncarl81... one of these days we need to talk about the value of documentation.
I'd love to know what other things I'm missing out on in Parceler that's not included on the README

**Comment by johncarl81** [comment]
I'm actually adding this tidbit to the documentation right now.

I'm also a big fan of forkable, PR'able, community driven documentation.  If you want to issue a PR to update the README or http://parceler.org/: https://github.com/johncarl81/parceler-site, be my guest.

**Comment by twig** [comment]
I'll try to decipher some of the code in Annotation land after work. If I can make sense of how the arguments work then I'll poke around some of the classes I use often and see what needs documenting.

**Comment by twig** [comment]
Thanks for the prompt reply by the way, much appreciated.

**Comment by johncarl81** [comment]
#152 and https://github.com/johncarl81/parceler-site/pull/4

**Comment by johncarl81** [comment]
Cool, sounds great @twig :+1:
