### ISSUE TITLE
Can not generate apk

### ISSUE THREAD

**Issue by rakjang007** [johncarl81/parceler#161]
I can not generate apk when add parceler dependency in two modules(App module, Library module).

this is error show when i generate apk.

`com.android.dex.DexException: Multiple dex files define Lorg/parceler/Parceler$$Parcels$1;`

i solve this problem by delete dependency in app module. but when i use .wrap() will be error.

`org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for ixx.xxx.xxx.dao.NewsItemDao, verify that your class is configured properly and that the Parcelable class ixx.xxx.xxx.dao.NewsItemDao$$Parcelable is generated by Parceler.
                                                                         at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:201)
                                                                         at org.parceler.Parcels.wrap(Parcels.java:85)
                                                                         at org.parceler.Parcels.wrap(Parcels.java:69)`

how to solve this problem?

**Comment by johncarl81** [comment]
http://parceler.org/#avoiding_parcels_indexing

**Comment by rakjang007** [comment]
Thank you johncarl81

I use @Parcel(parcelsIndex = false) in all parcel class.

This way is successful.
