### ISSUE TITLE
Can not Parcels.wrap() as expected

### ISSUE THREAD

**Issue by dgngulcan** [johncarl81/parceler#164]
When I try to wrap my Parcel annotated class it gives a RuntimeException like below.

SpeedModel class
```
@Parcel
public class SpeedModel {
    public long time;
    public double speed;

    public SpeedModel() {/* required for parcelable*/
    }

    public SpeedModel(double speed, long time) {
        this.speed = speed;
        this.time = time;
    }

}
```

Where error happens
```
SpeedModel speedModel = new SpeedModel();
Parcelable wrapped = Parcels.wrap(speedModel);
```

Error itself
```
FATAL EXCEPTION: main
                                                                    Process: com.paxotic.paxira, PID: 17878
                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.paxotic.paxira/com.paxotic.paxira.ui.activities.MainActivity}: org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for com.paxotic.paxira.data.models.SpeedModel, verify that your class is configured properly and that the Parcelable class com.paxotic.paxira.data.models.SpeedModel$$Parcelable is generated by Parceler.
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                        at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                     Caused by: org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for com.paxotic.paxira.data.models.SpeedModel, verify that your class is configured properly and that the Parcelable class com.paxotic.paxira.data.models.SpeedModel$$Parcelable is generated by Parceler.
                                                                        at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:201)
                                                                        at org.parceler.Parcels.wrap(Parcels.java:85)
                                                                        at org.parceler.Parcels.wrap(Parcels.java:69)
                                                                        at com.paxotic.paxira.ui.activities.MainActivity.testParcel(MainActivity.java:104)
                                                                        at com.paxotic.paxira.ui.activities.MainActivity.onCreate(MainActivity.java:63)
                                                                        at android.app.Activity.performCreate(Activity.java:6245)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

However, when I put my speedModel in array and wrap it, it wraps like this

 ```
SpeedModel activityModel = new SpeedModel();
        List<SpeedModel> list = new ArrayList<>();
        list.add(activityModel);
        Parcelable wrapped = Parcels.wrap(activityModel);
```
Is there a way that I can do it without creating new objects?

**Comment by dgngulcan** [comment]
It was due to poorly added gradle imports. fixed.
