### ISSUE TITLE
Parceler doesn't work with lambda expression and JavaVersion.VERSION_1_8

### ISSUE THREAD

**Issue by juergenzimmermann** [johncarl81/parceler#201]
I tried to use Lambda expressions and switched to JavaVersion.VERSION_1_8 in build.gradle. Now I'm getting this stacktrace:
````
05-30 20:57:00.471 2765-2765/de.shop E/AndroidRuntime: FATAL EXCEPTION: main
                                                       Process: de.shop, PID: 2765
                                                       org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for de.shop.data.Kunde, verify that your class is configured properly and that the Parcelable class de.shop.data.Kunde$$Parcelable is generated by Parceler.
                                                           at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:153)
                                                           at org.parceler.Parcels.wrap(Parcels.java:72)
                                                           at org.parceler.Parcels.wrap(Parcels.java:56)
                                                           at de.shop.ui.main.Main.-de_shop_ui_main_Main_lambda$1(Main.java:74)
                                                           at de.shop.ui.main.Main$-void_onCreate_android_os_Bundle_savedInstanceState_LambdaImpl0.onClick(Main.java)
                                                           at android.view.View.performClick(View.java:5609)
                                                           at android.view.View$PerformClick.run(View.java:22267)
                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                           at android.os.Looper.loop(Looper.java:154)
                                                           at android.app.ActivityThread.main(ActivityThread.java:5969)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)
````

**Comment by johncarl81** [comment]
Looks like the Parceler annotation processor isn't generating code.  Can you give me a concrete example that I can reproduce the problem?

**Comment by juergenzimmermann** [comment]
OK, tomorrow I'll put together a small project.

**Comment by juergenzimmermann** [comment]
The attached testcase is built with the latest Android Studio 2.2 Preview 2. You can install the testcase as follows:
* Create a project called "Shop" with company domain "shop.de" and package name "de.shop"
* Copy the files of the attached zip file into the project's subdirectory "app"
* Run the testcase (I was using the emulator with a 7" tablet for Android N)
* Click the button "Search"
[testcase-parceler.zip](https://github.com/johncarl81/parceler/files/293353/testcase-parceler.zip)

**Comment by johncarl81** [comment]
I won't be able to try this out before this evening, but there may be a couple issues here...
1.  `compile "org.parceler:parceler:${parcelerVersion}"` is definitely the wrong scope, it should be some sort of `apt` or `provided` scope.
2.  Not sure what the current status of Jack annotation processing is.  I heard that it will be included but I'm not sure what its current status is.

**Comment by juergenzimmermann** [comment]
Thank you @johncarl81. When using Java 8 (and thus jake) then the `dependencies` section in build.gradle has to be changed to:
````
annotationProcessor "org.parceler:parceler:${parcelerVersion}"
````
See http://tools.android.com/tech-docs/jackandjill#TOC-Repackaging-support
Now, my Parceler-based app works as before.

**Comment by johncarl81** [comment]
Hey, good news, I'll have to change the docs when it's out of beta.

Close issue?

**Comment by juergenzimmermann** [comment]
Extending the docs should be fine.
