### ISSUE TITLE
Parcel: unable to marshal value

### ISSUE THREAD

**Issue by Protino** [johncarl81/parceler#233]
I keep getting this error even though I haven't unwrapped anything at the receiver end.

This is my model `Movie class` : https://github.com/Protino/Fad-Flicks/blob/feature/app/src/main/java/com/calgen/prodek/fadflicks/model/Movie.java

This is how I am wrapping and unwrapping .

            //wrapping
            Intent intent = new Intent(mContext, Test.class);
            intent.putExtra(Intent.EXTRA_TEXT, Parcels.wrap(movie)); // movie object of Movie class
            mContext.startActivity(intent);

            //unwrapping
            Movie movie = Parcels.unwrap(getIntent().getParcelableExtra(Intent.EXTRA_TEXT));

I debugged with android studio debugger and found that it's reading the values correctly with absolutely no problem but all of a sudden the following error occurs and it crashes.

It occurs even when I've not used Parcels.unwrap and Parcels.wrap !

You can check it by building the project yourself - https://github.com/Protino/Fad-Flicks/commit/7c773d1fc40bad3519466d78bbf55f8a98959a33

Note : You need to get API_KEY from https://www.themoviedb.org for real data else configure the 
`fetchData` function in `DetailActivityFragment` to add fake data.

The error log is here : 
```                                                                          java.lang.RuntimeException: Parcel: unable to marshal value com.calgen.prodek.fadflicks.model.Movie@1ac6930
                                                                               at android.os.Parcel.writeValue(Parcel.java:1337)
                                                                               at android.os.Parcel.writeList(Parcel.java:711)
                                                                               at android.os.Parcel.writeValue(Parcel.java:1284)
                                                                               at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
                                                                               at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
                                                                               at android.os.Bundle.writeToParcel(Bundle.java:1096)
                                                                               at android.os.Parcel.writeBundle(Parcel.java:663)
                                                                               at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:138)
                                                                               at android.os.Parcel.writeTypedArray(Parcel.java:1191)
                                                                               at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:385)
                                                                               at android.os.Parcel.writeParcelable(Parcel.java:1357)
                                                                               at android.os.Parcel.writeValue(Parcel.java:1262)
                                                                               at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
                                                                               at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
                                                                               at android.os.Bundle.writeToParcel(Bundle.java:1096)
                                                                               at android.os.Parcel.writeBundle(Parcel.java:663)
                                                                               at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2884)
                                                                               at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3261)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)```

**Comment by johncarl81** [comment]
I'm not 100% sure, but my guess is proguard is removing the generated classes.  Here's the fix: https://github.com/Protino/Fad-Flicks/pull/2

**Comment by Protino** [comment]
Thanks for replying. But, that didn't help it still crashes. I created a whole new project and tested parceler between two activities, it works fine then.

Maybe there is some problem with my fragment lifecycles or some other library is interfering . I'll check and reply.

**Comment by johncarl81** [comment]
Hmm, I'm not sure then, any progress on your end @Protino?

**Comment by rpandey66** [comment]
Hello Protino for your error just do one thing 
Implement your Model class with Serializable eg. class Model implements Serializable
thats it.
I think you are created a class name Model and you are using it like streaming of data 
so you need to make it serializable by using normal implementation.
If it dosen't work or you are unable to use it just give me message here i'll give you detail expalnation

**Comment by Protino** [comment]
@johncarl81 No progress. I've looked into it since then. Maybe I'll try with the newer version and see how it goes.

@rpandey66 My model class does implement `serializable`. I think there was some problem with the proguard or some other library. Thanks for the help 👍

**Comment by johncarl81** [comment]
Implementing `Serializable` kind of defeats the purpose here.

**Comment by hazexzo** [comment]
Maybe anyone can help me with my similar problem?  https://stackoverflow.com/questions/45775269/parcel-unable-to-marshal-value-android-widget-linearlayout

**Comment by johncarl81** [comment]
Again, implementing `Serializable` defeats the purpose.  The equivalent code that uses Parceler @PrettyPreety  would be the following:
```java
ArrayList myList = new ArrayList();
intent.putParcelable("mylist", Parcels.wrap(myList));

In the other Activity:
ArrayList myList = Parcels.unwrap(getIntent().getParcelableExtra("mylist"));
```

**Comment by HarminderKhurana** [comment]
I open a Activity from fragment using Intent and also pass some value to activity , data reaches activity and after 1 or 2 sec app crashes and LogCat shows 
java.lang.RuntimeException: Parcel: unable to marshal value PostDataModel(......), with complete my model data , I do not use Any Parcelable or Serilizable .
except this I try to open only activity and not passing any data to it then also App crashes when Activity open with same error , can anyone help me >>>>????????

**Comment by johncarl81** [comment]
Maybe share some code @HarminderKhurana  and we can help?  From your description, it sounds like you're not passing in an object marshaled by Parcler.

**Comment by Umesh-01** [comment]
@johncarl81 @Protino @rpandey66 @PrettyPreety  @HarminderKhurana 
Someone please help me..

I am also getting the same error-
```error
java.lang.RuntimeException: Parcel: unable to marshal value SongsInfo(songName=AUD-20210504-WA0000.opus, artistName=<unknown>, imagepath=content://media/external/audio/albumart/2180172427474075056, songDuration=63220, songURL=/storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Audio/AUD-20210504-WA0000.opus)
```


Here is my SongsInfo class-
```kotlin
data class SongsInfo(
    val songName: String,
    val artistName: String,
    val imagepath: String,
    val songDuration: Int,
    val songURL: String
        )
```

First I am receiving this data in RecyclerAdapter.
Now, I want to pass this data from RecyclerAdapter to MusicPlayerActivity class.

Code in RecyclerAdapter (for sending)-

```kotlin
class RecyclerViewSongAdapter(val context: Context, val songsInfo: ArrayList<SongsInfo>): RecyclerView.Adapter<RecyclerViewSongAdapter.SongViewHolder>() {

// other code....

val intent = Intent(context, MusicPlayerActivity::class.java)
intent.putExtra("songsInfo", songsInfo)
```

Code in `MusicPlayerActivity` class (for receiving)-
```kotlin
var songsInformation: ArrayList<SongsInfo> = TODO()
// other code..
songsInformation = intent.getSerializableExtra("songsInfo") as ArrayList<SongsInfo>
```

**Comment by Protino** [comment]
@Umesh-01 You need to annotate your class with @parcel annotation and serialize and de-serialize using the methods Parcels.wrap ... and Parcels.unwrap...

Besides, there is https://developer.android.com/kotlin/parcelize library now which generates a Parcelable implementation.

**Comment by Umesh-01** [comment]
> @Umesh-01 You need to annotate your class with @parcel annotation and serialize and de-serialize using the methods Parcels.wrap ... and Parcels.unwrap...
> 
> Besides, there is https://developer.android.com/kotlin/parcelize library now which generates a Parcelable implementation.

should I write parcel in front of data class SongsInfo??
like this??

`@parcel`
`data class SongsInfo(`

**Comment by Umesh-01** [comment]
After somehow doing this 

I am getting this error when I try to play any music-
```
Attempt to invoke virtual method 'java.util.ArrayList android.content.Intent.getParcelableArrayListExtra(java.lang.String)' on a null object reference
```

OR

```
Attempt to invoke virtual method 'android.os.Parcelable android.content.Intent.getParcelableExtra(java.lang.String)' on a null object reference
```
