### ISSUE TITLE
Gradle and Parceler causing "Unable to create ParcelableFactory"?

### ISSUE THREAD

**Issue by ruqqq** [johncarl81/parceler#24]
I've set up build.gradle according to the example. Everything compiles fine but when I run the app an invoke Parcels.wrap, the app crashes. The project is set up with android-apt plugin and AndroidAnnotations which both are working fine.

```
org.parceler.ParcelerRuntimeException: Unable to create ParcelableFactory for sg.ruqqq.test.Item
E/AndroidRuntime(30134):    at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:182)
E/AndroidRuntime(30134):    at org.parceler.Parcels.wrap(Parcels.java:69)
```

Any help?

**Comment by Aqua-Ye** [comment]
Hi, I have the same issue when applying the plugin 'android-apt'.

Here is my build.gradle : 
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        // replace with the current version of the Android plugin
        classpath 'com.android.tools.build:gradle:1.0.0'
        // replace with the current version of the android-apt plugin
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
    }
}

repositories {
    mavenCentral()
    mavenLocal()
}

apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'

def AAVersion = '3.2'
def parcelerVersion = '0.2.15'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "com.tvshowtime.myapplication"
        minSdkVersion 14
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'

//    apt "org.androidannotations:androidannotations:$AAVersion"
//    compile "org.androidannotations:androidannotations-api:$AAVersion"

//    apt "org.parceler:parceler:${parcelerVersion}"
    compile "org.parceler:parceler-api:${parcelerVersion}"
    provided "org.parceler:parceler:${parcelerVersion}"
}

//apt {
//    arguments {
//        androidManifestFile variant.outputs[0].processResources.manifestFile
//        // if you have multiple outputs (when using splits), you may want to have other index than 0
//
//        resourcePackageName android.defaultConfig.applicationId
//
//        // If you're using Android NBS flavors you should use the following line instead of hard-coded packageName
//        // resourcePackageName android.defaultConfig.packageName
//
//        // You can set optional annotation processing options here, like these commented options:
//        // logLevel 'INFO'
//        // logFile '/var/log/aa.log'
//    }
//}
```
