### ISSUE TITLE
ClassNotFoundException when using Parceler with savedInstanceState

### ISSUE THREAD

**Issue by konradg** [johncarl81/parceler#25]
Steps to reproduce:
- Use Parcels.wrap() in onSaveInstanceState() method of a Fragment (from v4 support lib),
- Use Parcels.unwrap() in onActivityCreated() of the same Fragment.

Desired effect:
Reference to unmarshalled object returned from unwrap().

Current behavior:
Exception thrown: BadParcelableException: ClassNotFoundException when unmarshalling: [my_class]$$Parcelable

The $$Parcelable classes are created during build; the correct types are mapped in Parceler$$Parcels class. Problem does not appear when using custom Bundle instances (they use a BootClassLoader by default) or passing in an Intent (where the extras bundle uses a PathClassLoader). Checked on Nexus 5 with Android 4.4, Nexus 4 with 4.4.2, (both with ART runtime), Galaxy S3 (4.3.1, dalvik).

**Comment by ardoramor** [comment]
I'm getting the same exception when trying to explicitly add an account with AccountManager's user data:

    SessionToken sessionToken = mAuthClient.login(username, password);
    
    Bundle userData = new Bundle();
    userData.putParcelable(KEY_SESSION_DETAILS, Parcels.wrap(sessionToken));
    
    final Account account = new Account(accountName, accountType);
    
    // throws android.os.BadParcelableException
    mAccountManager.addAccountExplicitly(account, null, userData);

The following is the exception trace:

	10353-10353/com.abcdef.production E/AndroidRuntime﹕ FATAL EXCEPTION: main
		Process: com.abcdef.production, PID: 10353
		android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.abcdef.uv.model.SessionToken$$Parcelable
				at android.os.Parcel.readException(Parcel.java:1474)
				at android.os.Parcel.readException(Parcel.java:1426)
				at android.accounts.IAccountManager$Stub$Proxy.addAccountExplicitly(IAccountManager.java:719)
				at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:612)
				at com.abcdef.ui.LoginActivity.completeAuthentication(LoginActivity.java:316)
				at com.abcdef.ui.LoginActivity.access$500(LoginActivity.java:38)
				at com.abcdef.ui.LoginActivity$AuthenticateUserTask.onPostExecute(LoginActivity.java:235)
				at com.abcdef.ui.LoginActivity$AuthenticateUserTask.onPostExecute(LoginActivity.java:171)
				at android.os.AsyncTask.finish(AsyncTask.java:632)
				at android.os.AsyncTask.access$600(AsyncTask.java:177)
				at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
				at android.os.Handler.dispatchMessage(Handler.java:102)
				at android.os.Looper.loop(Looper.java:136)
				at android.app.ActivityThread.main(ActivityThread.java:5146)
				at java.lang.reflect.Method.invokeNative(Native Method)
				at java.lang.reflect.Method.invoke(Method.java:515)
				at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
				at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
				at dalvik.system.NativeStart.main(Native Method)

I tried setting class loader of activity but that didn't fix the issue:

    userData.setClassLoader(this.getClassLoader());

Is this a fault on my, AccountManager's, or Parceler's side?

**Comment by johncarl81** [comment]
Can you verify that `SessionToken$$Parcelable` is generated?

**Comment by ardoramor** [comment]
Yep, it is generated and I'm able to successfully wrap and unwrap it in other instances. However, I think I might have jumped the gun. I've read up more on AccountManager's userData and see that, although it does that a bundle, the bundle should only store String objects. Its not very obvious but it makes sense. Just ignore the above post :) !

**Comment by johncarl81** [comment]
Gotcha, glad you found a solution.  As always, feel free to post if anything else doesn't behave the way it should.
