### ISSUE TITLE
Parceler "magically" wraps non-annotated class on rotation, but crashes on activity pause

### ISSUE THREAD

**Issue by seasox** [johncarl81/parceler#269]
My list fragments extend a common class `MyRecyclerFragment<T>` with a member `List<T> list`.
For example I have` CustomerListFragment extends MyRecyclerFragment<Customer>`. During refactoring, I figured that `List<Customer> list` with `Customer` not being annotated with `@Parcel`, can be wrapped using `Parcels.wrap(LIST_KEY, list)`, while `Parcels.wrap(list.get(0))` throws `ParcelerRuntimeException`. Customer is a SimpleXML POJO consisting of `@Parcel` annotated members only. I am a confused how Parceler can wrap the list. My `build/generated/source/apt/debug` folder does not contain a `Customer$$Parcelable` class. I seem to misunderstand how Parceler works in this case.

I created a gist to reproduce this issue: https://gist.github.com/seasox/039b07e08e0890961c12a79f0cd367ed

Can anybody explain how Parcels.wrap works here? Thanks in advance.

**Comment by seasox** [comment]
During further debugging, I encountered a crash after I started another activity: 
```
03-06 14:58:12.490 22238-22238/de.fizon.henry E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: de.fizon.henry, PID: 22238
                                                                org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for de.fizon.henry.customer.Customer, verify that your class is configured properly and that the Parcelable class de.fizon.henry.customer.Customer$$Parcelable is generated by Parceler.
                                                                    at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:153)
                                                                    at org.parceler.Parcels.wrap(Parcels.java:72)
                                                                    at org.parceler.Parcels.wrap(Parcels.java:56)
                                                                    at org.parceler.NonParcelRepository$ListParcelable$1.itemToParcel(NonParcelRepository.java:288)
                                                                    at org.parceler.converter.CollectionParcelConverter.toParcel(CollectionParcelConverter.java:38)
                                                                    at org.parceler.converter.CollectionParcelConverter.toParcel(CollectionParcelConverter.java:27)
                                                                    at org.parceler.NonParcelRepository$ConverterParcelable.writeToParcel(NonParcelRepository.java:1230)
                                                                    at org.parceler.NonParcelRepository$ListParcelable.writeToParcel(NonParcelRepository.java:277)
                                                                    at android.os.Parcel.writeParcelable(Parcel.java:1496)
                                                                    at android.os.Parcel.writeValue(Parcel.java:1402)
                                                                    at android.os.Parcel.writeArrayMapInternal(Parcel.java:724)
                                                                    at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
                                                                    at android.os.Bundle.writeToParcel(Bundle.java:1157)
                                                                    at android.os.Parcel.writeBundle(Parcel.java:764)
                                                                    at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:150)
                                                                    at android.os.Parcel.writeTypedArray(Parcel.java:1307)
                                                                    at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:564)
                                                                    at android.os.Parcel.writeParcelable(Parcel.java:1496)
                                                                    at android.os.Parcel.writeValue(Parcel.java:1402)
                                                                    at android.os.Parcel.writeArrayMapInternal(Parcel.java:724)
                                                                    at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
                                                                    at android.os.Bundle.writeToParcel(Bundle.java:1157)
                                                                    at android.os.Parcel.writeBundle(Parcel.java:764)
                                                                    at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3633)
                                                                    at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3773)
                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Why does wrapping in onSaveInstanceState (in case of configuration change) work, but crashes when I start another activity?

**Comment by johncarl81** [comment]
Why share the project as a series of gists?  Why not just share the project as a github repo?

**Comment by johncarl81** [comment]
And should `Foo` be annotated with `@Parcel`?

**Comment by seasox** [comment]
I've created a repo: https://github.com/seasox/ParcelerMagic

No, `Foo` should not be annotated. That's the point about this issue. `List<Foo>` can be wrapped despite `Foo` not being annotated with `@Parcel` on orientation change, but throws on Activity pause.

**Comment by grandstaish** [comment]
That's because `writeToParcel`/`createFromParcel` never gets called on config changes. Android realises it's just changing config and keeps the object in memory rather than writing it to disk for no reason. Basically what you're doing is putting a "`Parcelable`" object (the list) filled with non-supported items (the `Foo`s) into a `Bundle`. Android will only realise this is a faux-`Parcelable` object once it tries to write the items and throws an exception. You'll need to annotate `Foo` with `@Parcel` or use the `@ParcelClass` API in this instance.

**Comment by seasox** [comment]
Ah, I see. I didn't know objects were kept in memory in case of config change (and wondered how the address of objects keeps the same on config change). Thank you for the explanation.
