### ISSUE TITLE
Unable to find generated Parcelable class when backgrounding a Fragment.

### ISSUE THREAD

**Issue by s73v3r** [johncarl81/parceler#314]
I have a POJO class that I've annotated with Parceler. It has 4 items: 3 are integers (resource references), and the other is a Generic Type T. This is an enum type. I use it to pass in a bundle to a DialogFragment. It works just fine, displaying what I passed in, and passing out the T type on selection in the DialogFragment.  I am adding it to the bundle like this: `        args.putParcelable(OPTIONS_ARG, Parcels.wrap(options));`, and retrieving it like this: `            options = (List<InfluencerOption>) Parcels.unwrap(args.getParcelable(OPTIONS_ARG));`. Options is declared as a `List<InfluencerOption>`. However, if I background the DialogFragment, I get a crash, saying that Parceler can't find the class.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.my.app, PID: 21649
    org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for com.my.app.InfluencerOption, verify that your class is configured properly and that the Parcelable class com.my.app.InfluencerOption$$Parcelable is generated by Parceler.
        at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:153)
        at org.parceler.Parcels.wrap(Parcels.java:72)
        at org.parceler.Parcels.wrap(Parcels.java:56)
        at org.parceler.NonParcelRepository$ListParcelable$1.itemToParcel(NonParcelRepository.java:288)
        at org.parceler.converter.CollectionParcelConverter.toParcel(CollectionParcelConverter.java:38)
        at org.parceler.converter.CollectionParcelConverter.toParcel(CollectionParcelConverter.java:27)
        at org.parceler.NonParcelRepository$ConverterParcelable.writeToParcel(NonParcelRepository.java:1230)
        at org.parceler.NonParcelRepository$ListParcelable.writeToParcel(NonParcelRepository.java:277)
        at android.os.Parcel.writeParcelable(Parcel.java:1437)
        at android.os.Parcel.writeValue(Parcel.java:1343)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:686)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
        at android.os.Bundle.writeToParcel(Bundle.java:1079)
        at android.os.Parcel.writeBundle(Parcel.java:711)
        at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:148)
        at android.os.Parcel.writeTypedArray(Parcel.java:1254)
        at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:564)
        at android.os.Parcel.writeParcelable(Parcel.java:1437)
        at android.os.Parcel.writeValue(Parcel.java:1343)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:686)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
        at android.os.Bundle.writeToParcel(Bundle.java:1079)
        at android.os.Parcel.writeBundle(Parcel.java:711)
        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3153)
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3417)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

I'm adding it like this: 
```
    compile 'org.parceler:parceler-api:1.1.9'
    annotationProcessor 'org.parceler:parceler:1.1.9'
```

**Comment by carmas123** [comment]
Have you tryied to rebuild project?
Have you tryied to use kapt and not annotationProcessor?

**Comment by s73v3r** [comment]
I've tried rebuilding the project several times to no avail. 

I have never heard of kapt, but when I tried using apt, lots of other parts of the app break for seemingly no reason.

**Comment by s73v3r** [comment]
I have multiple modules in my app. I have Parceler added to the main module, as well as another module that has classes in need of parceling. The main module uses the annotationProcessor directive, whereas the other one uses apt. I still get the same failure.

**Comment by carmas123** [comment]
I've same problem but solved when I rebuild project....

**Comment by s73v3r** [comment]
Not me. Still crashes.

**Comment by johncarl81** [comment]
Are you running proguard by chance?

**Comment by johncarl81** [comment]
Closing to do inactivity.

**Comment by zongxiaomi** [comment]
I had resolve this problem by change `annotationProcessor` to `kapt`,thank u
我通过使用 kap 解决了这个问题

**Comment by marvinceva** [comment]
> I had resolve this problem by change `annotationProcessor` to `kapt`,thank u
> 我通过使用 kap 解决了这个问题

this worked for me too !
