### ISSUE TITLE
Build fails when using @Parcel on generic type. Gives a null pointer exception

### ISSUE THREAD

**Issue by novus-logics** [johncarl81/parceler#326]
```
Caused by: java.lang.NullPointerException
        at org.parceler.transfuse.util.matcher.ASTTypeMatcher.matches(ASTTypeMatcher.java:52)
        at org.parceler.transfuse.util.matcher.ASTTypeMatcher.matches(ASTTypeMatcher.java:26)
        at org.parceler.internal.Generators.matches(Generators.java:45)
        at org.parceler.internal.ParcelableAnalysis.validateType(ParcelableAnalysis.java:645)
        at org.parceler.internal.ParcelableAnalysis.innerAnalyze(ParcelableAnalysis.java:315)
        at org.parceler.internal.ParcelableAnalysis.analyze(ParcelableAnalysis.java:68)
        at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:48)
        at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:31)
        at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
        at org.parceler.transfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
        at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
        at org.parceler.transfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
        at org.parceler.transfuse.transaction.Transaction.run(Transaction.java:77)
        at org.parceler.guava.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
        at org.parceler.transfuse.transaction.TransactionProcessorPool.execute(TransactionProcessorPool.java:60)
        at org.parceler.transfuse.transaction.TransactionProcessorComposite.execute(TransactionProcessorComposite.java:37)
        at org.parceler.transfuse.transaction.TransactionProcessorChain.execute(TransactionProcessorChain.java:38)
        at org.parceler.internal.ParcelProcessor.execute(ParcelProcessor.java:83)
        at org.parceler.ParcelAnnotationProcessor.process(ParcelAnnotationProcessor.java:84)

```

My main model is `BaseModel`
```
@Parcel
public class BaseModel {
    ...other stuff

    @Expose
    @SerializedName("info_one")
    public DataItem<SecondModel> infoOne;

    @Expose
    @SerializedName("info_two")
    public DataItem<List<ThirdModel>> infoTwo;

}
```

`SecondModel` defined below
```
@Parcel
public class SecondModel {
    ...other stuff

    @Expose
    @SerializedName("id")
    public int id;

    @Expose
    @SerializedName("title")
    public String title;

}
```

`ThirdModel` defined below
```
@Parcel
public class ThirdModel {
    ...other stuff

    @Expose
    @SerializedName("id")
    public int id;

    @Expose
    @SerializedName("image")
    public String image;

}
```

And finally, the `DataItem` is as below
```
@Parcel
public class DataItem<T> {

    @Expose
    @SerializedName("data")
    public T data;

}
```

**Comment by johncarl81** [comment]
I think we just fixed this error here: https://github.com/johncarl81/parceler/pull/325

What version are you running?  If you're not on 1.1.10 yet, upgrade.

**Comment by johncarl81** [comment]
I'm going to assume that fixed the issue.  Reopen if not.
