### ISSUE TITLE
Enums with Overridden methods

### ISSUE THREAD

**Issue by cody1024d** [johncarl81/parceler#328]
Hey @johncarl81, I don't have an example project, as I had to revert the changes to move forward, but I was running into Parceler not being able to find the generated class when I had the following usecase:

```Java
@Parcel
public enum TransferMode {
        SKELETON {
            public List<TaskRelatedModel> getModelsFromBundle(Bundle args) {
                List<SkeletonTask> retVal = ParcelUtil.get(args, MODE_KEY);
                return new ArrayList<>(retVal);
            }
        },
        TASK {
            public List<TaskRelatedModel> getModelsFromBundle(Bundle args) {
                List<Task> retVal = ParcelUtil.get(args, MODE_KEY);
                return new ArrayList<>(retVal);
            }
        };


        public abstract List<TaskRelatedModel> getModelsFromBundle(Bundle args);
    }
```

Basically Parceler was having a hard time finding a class for a TransferMode constant, and the error seemed to say it was looking for a parceler for TransferMode$1.  

I think it has something to do with the fact that each enum constant has it's own method (as I fixed this by using a switch statement in the enum itself).  

Here is the exception:

```java
FATAL EXCEPTION: main
                                                                        Process: com.fellowhipone.f1touch, PID: 4326
                                                                        org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for com.fellowhipone.f1touch.tasks.transfer.TransferTasksController$TransferMode$1, verify that your class is configured properly and that the Parcelable class com.fellowhipone.f1touch.tasks.transfer.TransferTasksController$TransferMode$1$$Parcelable is generated by Parceler.
                                                                            at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:153)
                                                                            at org.parceler.Parcels.wrap(Parcels.java:72)
                                                                            at org.parceler.Parcels.wrap(Parcels.java:56)```

**Comment by johncarl81** [comment]
Hmm, this works fine for me... can you put together an example or elaborate a bit?

**Comment by cody1024d** [comment]
Hey John, sorry about never moving forward with the above.  I moved past it in production, and it hadn't reared it's head again

**Comment by johncarl81** [comment]
No worries.  As always, feel free to reopen if you come across it again.
