### ISSUE TITLE
java.lang.UnsupportedOperationException: Minus sign spans multiple characters: ‏- (DecimalFormatSymbols)

### ISSUE THREAD

**Issue by Nietoperek** [johncarl81/parceler#330]
Hi
I'm using parceler v. 1.1.6. I'm getting error that's possibly connected to fixed issue https://android-review.googlesource.com/c/platform/libcore/+/149926 . 
Stack:
```
Fatal Exception: java.lang.UnsupportedOperationException: Minus sign spans multiple characters: ‏-
       at java.text.DecimalFormatSymbols.getMinusSign(DecimalFormatSymbols.java:300)
       at java.text.DecimalFormatSymbols.writeObject(DecimalFormatSymbols.java:611)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1033)
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
       at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:904)
       at java.io.ObjectOutputStream.writeFields(ObjectOutputStream.java:863)
       at java.text.DecimalFormat.writeObject(DecimalFormat.java:1129)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1033)
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
       at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
       at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
       at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
       at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
       at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
       at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
       at android.os.Parcel.writeSerializable(Parcel.java:1383)
       at android.os.Parcel.writeValue(Parcel.java:1335)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
       at android.os.Bundle.writeToParcel(Bundle.java:1096)
       at android.os.Parcel.writeBundle(Parcel.java:663)
       at android.support.v4.app.FragmentState.writeToParcel(FragmentState.java:120)
       at android.os.Parcel.writeTypedArray(Parcel.java:1191)
       at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:617)
       at android.os.Parcel.writeParcelable(Parcel.java:1357)
       at android.os.Parcel.writeValue(Parcel.java:1262)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
       at android.os.Bundle.writeToParcel(Bundle.java:1096)
       at android.os.Parcel.writeBundle(Parcel.java:663)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2987)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3497)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5576)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
```
Anyone has an idea how to fix this?
Happens on(at least): Lenovo/Samsung Android 5.0-5.1.1

**Comment by johncarl81** [comment]
I see you're using `Serializable` - this defeats the purpose of using `Parcelable`s.

Can you post some code to show what you're attempting?

**Comment by Nietoperek** [comment]
Unfortunately project is too big to find the chunk of code that's responsible for this error :(

**Comment by johncarl81** [comment]
Maybe that's part of your problem ;-P.  Can you look for a class in your domain graph that implements `Serializable`?
