### ISSUE TITLE
Unable to find generated Parcelable class

### ISSUE THREAD

**Issue by mallikgs** [johncarl81/parceler#332]
Hello, 

When I am using Parceler in a module, I am getting the below crash in release mode with proguard. 

Caused by: org.parceler.l: Unable to find generated Parcelable class for com.package.model.k, verify that your class is configured properly and that the Parcelable class com.package.model.k$$Parcelable is generated by Parceler.
                                                                           at org.parceler.Parcels$a.a(Unknown Source)
                                                                           at org.parceler.Parcels.a(Unknown Source)....

Upon going through the issues below, I have marked the Parcel models with ParcelsIndex=false to fix for duplicate zip exception. It seems to me that the proguard is obfuscating the classes with ParcelsIndex=false as there is seems to be no script to match the same.

https://github.com/johncarl81/parceler/issues/282
https://github.com/johncarl81/parceler/issues/198
https://github.com/johncarl81/parceler/issues/89

I have a  tried a few proguard scripts but none of them seems to work..Please help..

Here are my proguard scripts

-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}
-keep interface org.parceler.Parcel
-keep @org.parceler.Parcel class * { *; }
-keep class **$$Parcelable { *; }

**Comment by johncarl81** [comment]
What version are you using?  We removed `parcelsIndex` in release 1.1.3.  The latest is 1.1.10

**Comment by mallikgs** [comment]
I am using version 1.0.4. It seems the issue is resolved when I added the proguard scripts in my application proguard from library proguard. Thanks for the support
