### ISSUE TITLE
IndexOutOfBoundsException: Invalid index 6881395

### ISSUE THREAD

**Issue by venssy** [johncarl81/parceler#340]
I use parceler with _org.androidannotations_ and _CymChad:BaseRecyclerViewAdapterHelper_ , source code like this:
```java
@Parcel
public class Function {
  public CountMap glvars = new CountMap();
}

@Parcel(Parcel.Serialization.BEAN)
public class CountMap extends HashMap<String, Integer> {
	public CountMap(){}
}

@EActivity
public class FunctionActivity extends AppCompatActivity{
	@Extra
	Function function;
}
```

```java
// BaseItemDraggableAdapter for Function
FunctionActivity_.intent(this).function(adapter.getItem(i)).start();
```

It sometimes crash after dragging item, sometimes after swipe viewpager. If start activity at once without other performances , it's good most of the time.

I also try to make Function serialized as Serialization.BEAN , it dosen't work.
```
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 6881395, size is 24
    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
    at java.util.ArrayList.add(ArrayList.java:147)
    at org.parceler.IdentityCollection.put(IdentityCollection.java:49)
    at net.vensalary.autor.schema.CountMap$$Parcelable.read(CountMap$$Parcelable.java:79)
    at net.vensalary.autor.database.table.Project$$Parcelable.read(Project$$Parcelable.java:166)
    at net.vensalary.autor.database.table.Function$$Parcelable.read(Function$$Parcelable.java:105)
    at net.vensalary.autor.database.table.Function$$Parcelable$1.createFromParcel(Function$$Parcelable.java:29)
    at net.vensalary.autor.database.table.Function$$Parcelable$1.createFromParcel(Function$$Parcelable.java:24)
    at android.os.Parcel.readParcelable(Parcel.java:2367)
    at android.os.Parcel.readValue(Parcel.java:2264)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
    at android.os.BaseBundle.unparcel(BaseBundle.java:221)
    at android.os.BaseBundle.containsKey(BaseBundle.java:269)
```

**Comment by johncarl81** [comment]
Could you give me something more specific, like the exact case in which it's failing?

In general, I'd encourage you not to extend `HashMap` and instead just use a `Map` directly.

**Comment by johncarl81** [comment]
Closing due to inactivity.  Feel free to reopen.
