### ISSUE TITLE
Classloader cannot find class Serialization

### ISSUE THREAD

**Issue by pranaytokopedia** [johncarl81/parceler#350]
Platform - Windows
Android Studio - 3.1.3

JRE - 1.8.0_152
Parceler Version - 1.11

I am getting this error and building apk never succeeds. 
```
Caused by: java.lang.ClassNotFoundException: org.parceler.Parcel$Serialization
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more
```
 please let me know what should I do to fix this

**Comment by johncarl81** [comment]
Closing until a specific example is provided.
