### ISSUE TITLE
Extending android.location.Location

### ISSUE THREAD

**Issue by Gloix** [johncarl81/parceler#359]
Android's `Location` class is Parcelable and in my app I have a class extending Location that I want to make parcelable as well, however the following code does not work.

    @Parcel(Parcel.Serialization.BEAN)
    data class IndoorLocation @ParcelConstructor constructor(
        val floor: String?, val building: String?): Location("") {
    }

I get the following compile error:

    e: [kapt] An exception occurred: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at java.lang.String.substring(String.java:1963)
        at org.parceler.internal.ParcelableAnalysis.getPropertyName(ParcelableAnalysis.java:730)
        at org.parceler.internal.ParcelableAnalysis.access$100(ParcelableAnalysis.java:40)
        at org.parceler.internal.ParcelableAnalysis$3.apply(ParcelableAnalysis.java:402)
        at org.parceler.internal.ParcelableAnalysis$3.apply(ParcelableAnalysis.java:399)
        at org.parceler.internal.ParcelableAnalysis$10.apply(ParcelableAnalysis.java:474)
        at org.parceler.internal.ParcelableAnalysis$10.apply(ParcelableAnalysis.java:471)
        at org.parceler.guava.collect.Maps.toMap(Maps.java:1119)
        at org.parceler.guava.collect.Maps.toMap(Maps.java:1097)
        at org.parceler.guava.collect.FluentIterable.toMap(FluentIterable.java:424)
        at org.parceler.internal.ParcelableAnalysis.findValueMethods(ParcelableAnalysis.java:471)
        at org.parceler.internal.ParcelableAnalysis.findJavaBeanWriteMethods(ParcelableAnalysis.java:393)
        at org.parceler.internal.ParcelableAnalysis.innerAnalyze(ParcelableAnalysis.java:153)
        at org.parceler.internal.ParcelableAnalysis.analyze(ParcelableAnalysis.java:68)
        at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:48)
        at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:31)
        at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
        at org.parceler.transfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
        at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
        at org.parceler.transfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
        at org.parceler.transfuse.transaction.Transaction.run(Transaction.java:77)
        at org.parceler.guava.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
        at org.parceler.transfuse.transaction.TransactionProcessorPool.execute(TransactionProcessorPool.java:60)
        at org.parceler.transfuse.transaction.TransactionProcessorComposite.execute(TransactionProcessorComposite.java:37)
        at org.parceler.transfuse.transaction.TransactionProcessorChain.execute(TransactionProcessorChain.java:38)
        at org.parceler.internal.ParcelProcessor.execute(ParcelProcessor.java:83)
        at org.parceler.ParcelAnnotationProcessor.process(ParcelAnnotationProcessor.java:84)
        at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:99)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1039)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1180)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
        at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:55)
        at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:27)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:213)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:178)
        at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:96)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:95)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:105)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:82)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:375)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:67)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:366)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:120)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:161)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:57)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:441)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:1020)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:101)
        at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:1062)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:1019)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:440)
        at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by johncarl81** [comment]
Do you get the exception if you don't extend Location?

In general, I'd recommend favoring composition over extension - make `Location` a field of `IndoorLocation`.

**Comment by Gloix** [comment]
I found that the issue is related to issue #322. android.location.Location has a method called `set` that given a Location instance, copies over its state to 'this' instance. This causes `ParcelableAnalysis`'s `getPropertyName` to get confused about the property name `set` is related to. I don't know about beans standards, but in this context this `set` method should not be accounted as a property setter.

Maybe Parceler should avoid treating methods starting with `set`, `get` and `is` whose suffix is empty as properties.

This would effectively fix Parceler crashes with methods named `set`, `get` and `is`, thus making it more robust, as well as improving the property detection algorithm (currently not taking into account empty prefixes).

**Comment by johncarl81** [comment]
You're looking in the right direction... [`Location`](https://developer.android.com/reference/android/location/Location) does have a ton of getters and setters that are probably innapropriate to serlialize.  Instead, it's already a `Parcelable`, so use it as such.  For Parceler to handle that you should use it via a property instead of extending it:

```java
@Parcel
public class IndoorLocation {
    String floor;
    String building;
    Location location;
    ....
}
```
^ And make that into a kotlin class:
```java
@Parcel(Serialization.BEAN)
data class IndoorLocation( val floor: String?, val building: String?, val location: Location)
```

**Comment by Gloix** [comment]
Oh, I see. Parcelable classes work better when used in composition because their serialization/deserialization logic is better isolated rather than modified through extension. Although I do think that composition is a good way to cope with Parcelable classes, it imposes a class structure developers might not want in their design (composition over inheritance). Correct me if I'm wrong. 🙂 Maybe this is inherent to how Parcelables work, but I do think that there are ways around it.

The end result of using composition is that I would have to access an IndoorLocation's location object each time I want to get its latitude or longitude, for example. This, unfortunately would impose a big change in my project since it's heavily location based and many accessors would have to be changed. 🙁 I know this is particular to my project, but I'm saying that some other developers might be in the same situation.

As for this issue, we may close it, since the culprit was discovered. Maybe some other issue should be created regarding Parcelable inheritance...

I submitted PR #361 to fix the crash I got in this issue. That should at least fix the crash.


Thank you for your help.

**Comment by johncarl81** [comment]
You're correct on the composition idea and how the logic is better isolated.

You could write delegate methods to ease the burden on the rest of your app:
```java
@Parcel
public class IndoorLocation {
    Location location;
    
    public double getLatitude() {
        return location.getLatitude();
    }
    public double getLongitude() {
        return location.getLongitude();
    }
    ....
}
```
Or hit Alt-Insert and select Delegate methods... in Android Studio.

From my perspective, inheritance is grossly overused in object oriented applications.  Developers seem to use it as a way of tacking on extra functionality when it should be used as a way of leveraging polymorphism in your application.  By tacking on this functionality your classes are literally inheriting a ton of baggage that is probably out of scope for the given class.  Of course, Android's API doesnt help this as everything is extended from some base class - perferring composition, on the other hand, gives you a lot more control over the API you are exposing in your domain (Location for instance has dozens of methods that are probably not appropriate for the domain).

**Comment by Gloix** [comment]
I see your point.
Unfortunately my project works with both `IndoorLocation` and `Location` instances and there are multiple parts in which I have `IndoorLocation` instances as `Location` type. To make the change you mention, a common interface would work better, but unfortunately Android's `Location` does not have one. At this point I'm thinking of making such common interface (e.g. `ILocation`) and make an inheriting class that delegates calls to Android's `Location`objects. I hope I'm on the right track.

**Comment by johncarl81** [comment]
Sounds good to me @Gloix!
