### ISSUE TITLE
Cannot get working with navigation graph

### ISSUE THREAD

**Issue by piotrros** [johncarl81/parceler#387]
Project compiles fine, but on startup crashes:

Caused by: java.lang.IllegalArgumentException: com.foo.bar.NotificationModel is not Serializable or Parcelable.
        at androidx.navigation.NavType.fromArgType(NavType.java:178)
        at androidx.navigation.NavInflater.inflateArgument(NavInflater.java:191)
        at androidx.navigation.NavInflater.inflateArgumentForDestination(NavInflater.java:155)
        at androidx.navigation.NavInflater.inflate(NavInflater.java:128)
        at androidx.navigation.NavInflater.inflate(NavInflater.java:141)
        at androidx.navigation.NavInflater.inflate(NavInflater.java:88)
        	... 37 more

If I remove @Parcel annotation and implement Parcelable interface by myself it works without any problems. How can I get this working?

**Comment by johncarl81** [comment]
Most likely because `NotificationModel` is not a Parcelable.  Do you want this serialized?
