### ISSUE TITLE
Crashing on background

### ISSUE THREAD

**Issue by arunkr83** [johncarl81/parceler#391]
org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for android.graphics.Path, verify that your class is configured properly and that the Parcelable class android.graphics.Path$$Parcelable is generated by Parceler.
        at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:154)
        at org.parceler.Parcels.wrap(Parcels.java:73)
        at org.parceler.Parcels.wrap(Parcels.java:57)
        at                                                     .PathListParcelConverter.itemToParcel(PathListParcelConverter.java:11)
        at                                                    .PathListParcelConverter.itemToParcel(PathListParcelConverter.java:8)
        at org.parceler.converter.CollectionParcelConverter.toParcel(CollectionParcelConverter.java:38)
        at                                                      .DrawingSticker$$Parcelable.write(DrawingSticker$$Parcelable.java:53)
        at                                                      .DrawingSticker$$Parcelable.writeToParcel(DrawingSticker$$Parcelable.java:44)
        at android.os.Parcel.writeParcelable(Parcel.java:1804)
        at android.os.Parcel.writeValue(Parcel.java:1710)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:931)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1593)
        at android.os.Bundle.writeToParcel(Bundle.java:1253)
        at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4627)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7551)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

 //Parceler
    implementation 'org.parceler:parceler-api:1.1.13'
    annotationProcessor 'org.parceler:parceler:1.1.13'

# Parceler library
-keep interface org.parceler.Parcel
-keep @org.parceler.Parcel class * { *; }
-keep class **$$Parcelable { *; }

Testing In debug mode. Working fine in foreground. Crashes when pressing home button (background). Using to save graphics path as Arraylist to restore on orientation change. New to android, forgive my bad English.

**Comment by johncarl81** [comment]
You probably shouldn't be attempting to generate a `Parcelable` for the android `Path` object.

**Comment by arunkr83** [comment]
May be. But working perfect in foreground (while orientation changes)

**Comment by arunkr83** [comment]
> 
> 
> You probably shouldn't be attempting to generate a `Parcelable` for the android `Path` object.


May be. But working perfect in foreground (while orientation changes)

**Comment by johncarl81** [comment]
probably because nothing is marshaled until the app is destroyed / goes to background

**Comment by arunkr83** [comment]
> 
> 
> probably because nothing is marshaled until the app is destroyed / goes to background

You are right. Path is not serializable. Solved the issue by using custom serializable path class. thank you for your time
