### ISSUE TITLE
Object without fields exception

### ISSUE THREAD

**Issue by tajchert** [johncarl81/parceler#64]
Using `@Parcel` annotation on object without fields results in error.

sample object:
 `import org.parceler.Parcel;
@Parcel
public class CustomObject {
    public CustomObject() {
    }
}`

Output:
`org.parceler.ParcelerRuntimeException: Unable to create ParcelableFactory for package.CustomObject
at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:198)
at org.parceler.Parcels.wrap(Parcels.java:85)
at org.parceler.Parcels.wrap(Parcels.java:69)
...`

To solve it adding same field (boolean, String etc.) is enough.

**Comment by tajchert** [comment]
Never mind, it crashed at `if(customObject  instanceof Parcelable)`
