### ISSUE TITLE
how can i set proguard file?

### ISSUE THREAD

**Issue by snowdream** [johncarl81/parceler#68]
i got an error, when i use proguard.

```java
E/AndroidRuntime(19786): Process: com.github.snowdream.android.apps.books, PID: 19786
E/AndroidRuntime(19786): org.parceler.v: Unable to create ParcelableFactory for com.github.snowdream.android.app.books.b.a
E/AndroidRuntime(19786):        at org.parceler.x.a(Unknown Source)
E/AndroidRuntime(19786):        at org.parceler.Parcels.a(Unknown Source)
E/AndroidRuntime(19786):        at org.parceler.NonParcelRepository$ListParcelable.writeToParcel(Unknown Source)
E/AndroidRuntime(19786):        at android.os.Parcel.writeParcelable(Parcel.java:1357)
E/AndroidRuntime(19786):        at android.os.Parcel.writeValue(Parcel.java:1262)
E/AndroidRuntime(19786):        at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
E/AndroidRuntime(19786):        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
E/AndroidRuntime(19786):        at android.os.Bundle.writeToParcel(Bundle.java:1096)
E/AndroidRuntime(19786):        at android.os.Parcel.writeBundle(Parcel.java:663)
E/AndroidRuntime(19786):        at android.support.v4.app.FragmentState.writeToParcel(Unknown Source)
E/AndroidRuntime(19786):        at android.os.Parcel.writeTypedArray(Parcel.java:1191)
E/AndroidRuntime(19786):        at android.support.v4.app.FragmentManagerState.writeToParcel(Unknown Source)
E/AndroidRuntime(19786):        at android.os.Parcel.writeParcelable(Parcel.java:1357)
E/AndroidRuntime(19786):        at android.os.Parcel.writeValue(Parcel.java:1262)
E/AndroidRuntime(19786):        at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
E/AndroidRuntime(19786):        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
E/AndroidRuntime(19786):        at android.os.Bundle.writeToParcel(Bundle.java:1096)
E/AndroidRuntime(19786):        at android.os.Parcel.writeBundle(Parcel.java:663)
E/AndroidRuntime(19786):        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2884)
E/AndroidRuntime(19786):        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3261)
E/AndroidRuntime(19786):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(19786):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(19786):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(19786):        at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime(19786):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19786):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(19786):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime(19786):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
W/ActivityManager(  746):   Force finishing activity com.github.snowdream.android.apps.books/com.github.snowdream.android.app.books.MainActivity
```

**Comment by johncarl81** [comment]
What does your proguard setup look like?  You will probably have to include the generated $$Parcelable wrapper classes.

**Comment by snowdream** [comment]
i just use the default proguard file

**Comment by johncarl81** [comment]
Ok, then you will have to add the generated $$Parcelable wrapper classes.

**Comment by snowdream** [comment]
Can you add it in the readme.md,or wiki?
I  think other use will also meet it.

2015-01-26 10:07 GMT+08:00 John Ericksen <notifications@github.com>:

> Ok, then you will have to add the generated $$Parcelable wrapper classes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/johncarl81/parceler/issues/68#issuecomment-71406646>.
>



-- 
杨辉
Impossible is nothing!



------------------------------------------------------------------------------------
HDExplorer APK (A Nice File Manager,Simplicity but not simple.）

Google Market：
https://market.android.com/details?id=com.hd.explorer

Google Code：
http://code.google.com/p/hdexplorer/

**Comment by johncarl81** [comment]
I'll consider it.  Thanks.
