### ISSUE TITLE
Parceler Template

### ISSUE THREAD

**Issue by ardoramor** [johncarl81/parceler#74]
I am trying to use Parceler to address the following issue. My app uses Retrofit. Parceler is used to send/receive JSON objects. Server always responds with the following structure:

    {
        "code": "OK",
        "message": "Successfully updated profile.",
        "data": {
             ...
        }
    }

I was unwrapping the data using `ItemTypeAdapterFactory`:

	private class ItemTypeAdapterFactory implements TypeAdapterFactory {

        public <T> TypeAdapter<T> create(Gson gson, final TypeToken<T> type) {

            final TypeAdapter<T> delegate = gson.getDelegateAdapter(this, type);
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);

            return new TypeAdapter<T>() {

                public void write(JsonWriter out, T value) throws IOException {
                    delegate.write(out, value);
                }

                public T read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);

                    if (jsonElement.isJsonObject()) {
                        JsonObject jsonObject = jsonElement.getAsJsonObject();

                        if (jsonObject.has("data") && jsonObject.get("data").isJsonObject()) {
                            jsonElement = jsonObject.get("data");
                        }
                    }

                    return delegate.fromJsonTree(jsonElement);
                }
            }.nullSafe();
        }
    }

However, I wanted to refactor it for a long time because of the following:

* I need to get the response message (more so for the error case)
* I think that the generally accepted ItemTypeAdapterFactory code will strip any `data` key not just in the root element (not tested but code looks like it)
* I'd like more control over it and possibly feeding that structure into RxAndroid for it to process it and strip it out

However, I do not want to define a bunch of root Parcelers for every type of response I may get.

As such, I thought it is possible to do the following:

	@Parcel
	public class BaseResponse<T> {
		private static final String RESPONSE_CODE_SUCCESS = "OK";
		private static final int STATUS_ERROR = 0;
		private static final int STATUS_OK = 1;
		
		public String code;
		public String message;
		@SerializedName("securityclassification")
		public String classification;
		
		public T data;

		public T getData() {
			return data;
		}
		
		public int getStatus() {
			if (code != null && RESPONSE_CODE_SUCCESS.equals(code.toUpperCase())) {
				return STATUS_OK;
			}
			else {
				return STATUS_ERROR;
			}
		}

		public String getErrorMessage() {
			return message;
		}
	}

And then, for a user profile, define something like this:

    // User parcel
	@Parcel
	public class UserProfile {
		public String name;
		public String email;
	}

    // API definition with Retrofit annotations
    @GET("/api/user/info")
    BaseResponse<UserProfile> getUserProfile(@Query("token") String apikey);

However, I get the following error when trying to build my application:

	Error:Exception in thread "pool-51-thread-1" java.lang.NullPointerException
		at com.sun.tools.javac.model.JavacElements.cast(JavacElements.java:632)
		at com.sun.tools.javac.model.JavacElements.getPackageOf(JavacElements.java:367)
		at org.parceler.transfuse.adapter.element.ASTElementFactory.buildPackageClass(ASTElementFactory.java:134)
		at org.parceler.transfuse.adapter.element.ASTElementFactory.buildType(ASTElementFactory.java:91)
		at org.parceler.transfuse.adapter.element.ASTElementFactory.getType(ASTElementFactory.java:78)
		at org.parceler.transfuse.adapter.element.ReloadableASTElementFactory$ReloadableASTTypeProvider.get(ReloadableASTElementFactory.java:65)
		at org.parceler.transfuse.adapter.element.ReloadableASTElementFactory$ReloadableASTTypeProvider.get(ReloadableASTElementFactory.java:53)
		at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:49)
		at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:34)
		at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
		at org.parceler.transfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
		at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
		at org.parceler.transfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
		at org.parceler.transfuse.transaction.Transaction.run(Transaction.java:77)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
		at java.lang.Thread.run(Thread.java:745)

	Exception in thread "pool-55-thread-1" java.lang.NullPointerException
		at com.sun.tools.javac.model.JavacElements.cast(JavacElements.java:632)
		at com.sun.tools.javac.model.JavacElements.getPackageOf(JavacElements.java:367)
		at org.parceler.transfuse.adapter.element.ASTElementFactory.buildPackageClass(ASTElementFactory.java:134)
		at org.parceler.transfuse.adapter.element.ASTElementFactory.buildType(ASTElementFactory.java:91)
		at org.parceler.transfuse.adapter.element.ASTElementFactory.getType(ASTElementFactory.java:78)
		at org.parceler.transfuse.adapter.element.ReloadableASTElementFactory$ReloadableASTTypeProvider.get(ReloadableASTElementFactory.java:65)
		at org.parceler.transfuse.adapter.element.ReloadableASTElementFactory$ReloadableASTTypeProvider.get(ReloadableASTElementFactory.java:53)
		at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:49)
		at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:34)
		at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
		at org.parceler.transfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
		at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)

		at org.parceler.transfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
	FAILURE: Build failed with an exception.
		at org.parceler.transfuse.transaction.Transaction.run(Transaction.java:77)

		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	* What went wrong:
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	Execution failed for task ':app:compileInternalDebugJava'.
		at java.lang.Thread.run(Thread.java:745)
	> org.parceler.transfuse.TransfuseAnalysisException: @Parcel code generation did not complete successfully.

I've checked the wiki to see if templating is supported and didn't see it... was hoping that **not** seeing that its **not** supported meant that it **is** supported :)

**Comment by johncarl81** [comment]
Ugh, Parceler errors need to be better than that.  My apologies.

The error is coming from the generic type variable (as you thought).  There are a few ways around this, but you will probably have to declare a more concrete type so Parceler can process it during compile time.  Could you define something like this instead:

```java
public abstract class BaseResponse<T> {
   ...
    public abstract T getData();
...
}
```
And your concrete UserProfile type:

```java
@Parcel
public class UserProfileResponse extends BaseResponse<UserProfile> {
    UserProfile data;
   ...
}
```

Then use it:

```java
// API definition with Retrofit annotations
@GET("/api/user/info")
UserProfileResponse getUserProfile(@Query("token") String apikey);
```

Anther way around this would be to use a `ParcelConverter` and `Parcels.wrap()`/`Parcels.unwrap()` to bridge the gap:

```java
@Parcel
public class GenericWrapper {

    @ParcelPropertyConverter(ParcelWrapperConverter.class)
    Object value;

    public static class ParcelWrapperConverter implements ParcelConverter{

        @Override
        public void toParcel(Object input, android.os.Parcel parcel) {
            parcel.writeParcelable(Parcels.wrap(input), 0);
        }

        @Override
        public Object fromParcel(android.os.Parcel parcel) {
            return ((ParcelWrapper)parcel.readParcelable(ParcelWrapperConverter.class.getClassLoader())).getParcel();
        }
    }
}
```
After looking at this deeper, we should be able to handle generics in the latter case.   I'll have to think on this and your input is always welcome.

**Comment by johncarl81** [comment]
Hmm, as a scab solution, you could use generics and simply define the value as an `Object` internally:

```java
@Parcel
public class BaseResponse<T> {
    private static final String RESPONSE_CODE_SUCCESS = "OK";
    private static final int STATUS_ERROR = 0;
    private static final int STATUS_OK = 1;

    public String code;
    public String message;
    @SerializedName("securityclassification")
    public String classification;

    @ParcelPropertyConverter(ParcelWrapperConverter.class)
    public Object data;

    public T getData() {
        return (T)data;
    }

    public int getStatus() {
        if (code != null && RESPONSE_CODE_SUCCESS.equals(code.toUpperCase())) {
            return STATUS_OK;
        }
        else {
            return STATUS_ERROR;
        }
    }

    public String getErrorMessage() {
        return message;
    }
}
```

**Comment by johncarl81** [comment]
FYI, I have part of this fixed, it looks like the generic types won't load if they are part of the type.  So, you need to use 0.2.17-SNAPSHOT for the time being.

**Comment by ardoramor** [comment]
Thanks for your responses! The first suggestion is what I was trying to avoid - having to define a response class for every unique API method. Though, extending does make things slightly easier as opposed to defining unrelated response classes.

I will have to try out the `ParcelWrapperConverter` suggestion. It looks like it should work though! Method `getData` will return template type. If I want to access `data` member directly, I will cast it. This doesn't work with primitive types but I don't think `data` is ever a primitive type in my server's API.

As for 0.2.17-SNAPSHOT, are you saying that a generic type parcel class is now able to compile but will not read in the value of the JSON object which maps to a generic type member of that parcel class?

**Comment by johncarl81** [comment]
It looks like version 0.2.17-SNAPSHOT fixes your issue, if you use the `ParcelWrapperConverter`.  Let me know if it works for you.

**Comment by johncarl81** [comment]
@ardoramor, did you have success with the SNAPSHOT and `ParcelWrapperConverter` approach?  I think I'd like to release a version with these updates.

**Comment by ardoramor** [comment]
Sorry for long pause but I was diverted from the project for a bit. It works and I haven't ran into issues. I mean, your whole project is a life saver!

**Comment by johncarl81** [comment]
Good to hear @ardoramor.  You good to close this issue?

**Comment by ardoramor** [comment]
Yep!
