### ISSUE TITLE
Does Parceler work with SugarORM?

### ISSUE THREAD

**Issue by RyanDawkins** [johncarl81/parceler#84]
SugarORM: http://satyan.github.io/sugar/

I'm getting an error with Parceler.
```
/Users/dawkins/Projects/GymApp/app/src/main/java/com/ryanddawkins/gymapp/Workout.java
Warning:(13, 20) Parceler: Reflection is required to modify private fields, consider using non-private.
Warning:(13, 20) Parceler: Reflection is required to access private fields, consider using non-private.
/Users/dawkins/Projects/GymApp/app/src/main/java/com/ryanddawkins/gymapp/Exercise.java
Error:(11, 2) error: cannot find symbol class Parcel
/Users/dawkins/Projects/GymApp/app/build/intermediates/classes/debug/com/orm/SugarRecord$$PackageHelper.java
Error:(14, 36) error: method accessSugarRecord$FG$tableName(SugarRecord) is already defined in class SugarRecord$$PackageHelper
Error:(22, 34) error: method accessSugarRecord$FG$id(SugarRecord) is already defined in class SugarRecord$$PackageHelper
Error:(30, 24) error: method accessSugarRecord$FS$tableName(SugarRecord,String) is already defined in class SugarRecord$$PackageHelper
Error:(38, 24) error: method accessSugarRecord$FS$id(SugarRecord,Long) is already defined in class SugarRecord$$PackageHelper
```

**Comment by RyanDawkins** [comment]
I tried adding @ParcelClass(SugarRecord.class) at the beginning of my MainAcitivty. This just led me to get another error:

```
Exception in thread "pool-186-thread-1" java.lang.NoClassDefFoundError: android/os/Parcel
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2688)
	at java.lang.Class.getDeclaredMethods(Class.java:1962)
	at org.androidtransfuse.adapter.classes.ASTClassFactory.buildType(ASTClassFactory.java:119)
	at org.androidtransfuse.adapter.classes.ASTClassFactory.getType(ASTClassFactory.java:72)
	at org.androidtransfuse.adapter.classes.ASTClassFactory.buildType(ASTClassFactory.java:109)
	at org.androidtransfuse.adapter.classes.ASTClassFactory.getType(ASTClassFactory.java:72)
	at org.androidtransfuse.adapter.classes.ASTClassFactory.getType(ASTClassFactory.java:63)
	at org.parceler.internal.ExternalParcelTransactionWorker.getConverterType(ExternalParcelTransactionWorker.java:78)
	at org.parceler.internal.ExternalParcelTransactionWorker.innerRun(ExternalParcelTransactionWorker.java:69)
	at org.parceler.internal.ExternalParcelTransactionWorker.innerRun(ExternalParcelTransactionWorker.java:36)
	at org.androidtransfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.androidtransfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
	at org.androidtransfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.androidtransfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
	at org.androidtransfuse.transaction.Transaction.run(Transaction.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
Error:java.lang.ClassNotFoundException: android.os.Parcel
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
Warning:File for type 'com.orm.SugarRecord$$Parcelable' created in the last round will not be subject to annotation processing.
Warning:File for type 'com.ryanddawkins.gymapp.Exercise$$Parcelable' created in the last round will not be subject to annotation processing.
/Users/dawkins/Projects/GymApp/app/src/main/java/com/ryanddawkins/gymapp/Workout.java
Warning:(13, 20) Parceler: Reflection is required to modify private fields, consider using non-private.
Warning:(13, 20) Parceler: Reflection is required to access private fields, consider using non-private.
Warning:File for type 'com.ryanddawkins.gymapp.Workout$$Parcelable' created in the last round will not be subject to annotation processing.
Warning:File for type 'org.parceler.Parceler$$Parcels' created in the last round will not be subject to annotation processing.
Warning:File for type 'com.orm.SugarRecord$$PackageHelper' created in the last round will not be subject to annotation processing.
/Users/dawkins/Projects/GymApp/app/build/intermediates/classes/debug/com/orm/SugarRecord$$PackageHelper.java
Error:(14, 36) error: method accessSugarRecord$FG$tableName(SugarRecord) is already defined in class SugarRecord$$PackageHelper
Error:(22, 34) error: method accessSugarRecord$FG$id(SugarRecord) is already defined in class SugarRecord$$PackageHelper
Error:(30, 24) error: method accessSugarRecord$FS$tableName(SugarRecord,String) is already defined in class SugarRecord$$PackageHelper
Error:(38, 24) error: method accessSugarRecord$FS$id(SugarRecord,Long) is already defined in class SugarRecord$$PackageHelper
7 warnings
Error:Execution failed for task ':app:compileDebugJava'.
> Compilation failed; see the compiler error output for details.
```

**Comment by johncarl81** [comment]
Im disappointed to see that this ORM requires a base class.

What version of Parceler are you using?

**Comment by johncarl81** [comment]
Oh, and I almost forgot, we have a new feature that allows you to only analyze/serialize part of a class based on the inheritnace higherarchy.  For instance:
```java
@Parcel(analyze = Workout.class)
public class Workout extends SugarRecord{...}
```
Will only serialize the Workout specific class variables.

**Comment by johncarl81** [comment]
@RyanDawkins, these approaches should work for you.  Feel free to reopen if you are having further difficulties.
