### ISSUE TITLE
org.parceler.x: Unable to create ParcelableFactory

### ISSUE THREAD

**Issue by androidfu** [johncarl81/parceler#91]
Full Source
https://github.com/androidfu/Now-Playing

I'm using v0.2.10 of Parceler:

```java
    compile 'org.parceler:parceler-api:0.2.10'
    provided 'org.parceler:parceler:0.2.10'
```

I have the following Proguard rules:

```java
 # Parceler configuration
 -keep interface org.parceler.Parcel
 -keep @org.parceler.Parcel class * { *; }
 -keep class **$$Parcelable { *; }
 -keep class org.parceler.Parceler$$Parcels
```

I'm calling this
```java
public class MovieListFragment extends Fragment {
    private static final String KEY_BUNDLE_MOVIES = "movieList";
    private List<Movie> mMovies = new ArrayList<>();

    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        outState.putParcelable(KEY_BUNDLE_MOVIES, Parcels.wrap(mMovies));
    }
}
```

Here's a snippet of Movie:

```java
@Parcel
@DebugLog
public class Movie {
    @Expose
    public String id;
    // ...
}
```

The error only happens when I have a populated list of Movies:

```java
04-26 12:00:26.288  32271-32271/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.androidfu.nowplaying.app, PID: 32271
    org.parceler.x: Unable to create ParcelableFactory for com.androidfu.nowplaying.app.model.movies.Movie
            at org.parceler.z.a(Parcels.java:182)
            at org.parceler.Parcels.a(Parcels.java:69)
            at org.parceler.NonParcelRepository$ListParcelable.writeToParcel(NonParcelRepository.java:170)
            at android.os.Parcel.writeParcelable(Parcel.java:1363)
            at android.os.Parcel.writeValue(Parcel.java:1268)
            at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
            at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
            at android.os.Bundle.writeToParcel(Bundle.java:1034)
            at android.os.Parcel.writeBundle(Parcel.java:669)
            at android.app.FragmentState.writeToParcel(Fragment.java:139)
            at android.os.Parcel.writeTypedArray(Parcel.java:1197)
            at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:376)
            at android.os.Parcel.writeParcelable(Parcel.java:1363)
            at android.os.Parcel.writeValue(Parcel.java:1268)
            at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
            at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
            at android.os.Bundle.writeToParcel(Bundle.java:1034)
            at android.os.Parcel.writeBundle(Parcel.java:669)
            at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2919)
            at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3296)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by androidfu** [comment]
I turned off Proguard as a precaution.  It make no difference.

```java
04-26 12:41:19.907  14829-14829/com.androidfu.nowplaying.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.androidfu.nowplaying.app, PID: 14829
    org.parceler.ParcelerRuntimeException: Unable to create ParcelableFactory for com.androidfu.nowplaying.app.model.movies.Movie
            at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:182)
            at org.parceler.Parcels.wrap(Parcels.java:69)
            at org.parceler.NonParcelRepository$ListParcelable.writeToParcel(NonParcelRepository.java:170)
            at android.os.Parcel.writeParcelable(Parcel.java:1363)
            at android.os.Parcel.writeValue(Parcel.java:1268)
            at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
            at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
            at android.os.Bundle.writeToParcel(Bundle.java:1034)
            at android.os.Parcel.writeBundle(Parcel.java:669)
            at android.app.FragmentState.writeToParcel(Fragment.java:139)
            at android.os.Parcel.writeTypedArray(Parcel.java:1197)
            at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:376)
            at android.os.Parcel.writeParcelable(Parcel.java:1363)
            at android.os.Parcel.writeValue(Parcel.java:1268)
            at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
            at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
            at android.os.Bundle.writeToParcel(Bundle.java:1034)
            at android.os.Parcel.writeBundle(Parcel.java:669)
            at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2919)
            at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3296)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by johncarl81** [comment]
Hmm, first thought it to upgrade to the latest 0.2.16.

**Comment by androidfu** [comment]
Did.  I ended up using "apt" instead of "provided".  Fixed the issue.

**Comment by johncarl81** [comment]
Were you using other libraries with apt scope?

**Comment by androidfu** [comment]
I was not.
