### ISSUE TITLE
Build fail: org.parceler.ParcelerRuntimeException

### ISSUE THREAD

**Issue by evasyuk** [johncarl81/parceler#92]
Could you give me advice what makes error bellow to apear?
```
Exception in thread "pool-20-thread-1" org.parceler.ParcelerRuntimeException: Unable to find appropriate Parcel method to write java.lang.Object
	at org.parceler.internal.Generators.getGenerator(Generators.java:49)
	at org.parceler.internal.generator.MapReadWriteGenerator.generateReader(MapReadWriteGenerator.java:91)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcelExpression(ParcelableGenerator.java:282)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcel(ParcelableGenerator.java:234)
	at org.parceler.internal.ParcelableGenerator.buildParcelRead(ParcelableGenerator.java:166)
	at org.parceler.internal.ParcelableGenerator.generateParcelable(ParcelableGenerator.java:100)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:54)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:34)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
	at org.parceler.transfuse.transaction.Transaction.run(Transaction.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-22-thread-1" org.parceler.ParcelerRuntimeException: Unable to find appropriate Parcel method to write java.lang.Object
	at org.parceler.internal.Generators.getGenerator(Generators.java:49)
	at org.parceler.internal.generator.MapReadWriteGenerator.generateReader(MapReadWriteGenerator.java:91)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcelExpression(ParcelableGenerator.java:282)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcel(ParcelableGenerator.java:234)
	at org.parceler.internal.ParcelableGenerator.buildParcelRead(ParcelableGenerator.java:166)
	at org.parceler.internal.ParcelableGenerator.generateParcelable(ParcelableGenerator.java:100)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:54)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:34)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
	at org.parceler.transfuse.transaction.Transaction.run(Transaction.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-24-thread-1" org.parceler.ParcelerRuntimeException: Unable to find appropriate Parcel method to write java.lang.Object
	at org.parceler.internal.Generators.getGenerator(Generators.java:49)
	at org.parceler.internal.generator.MapReadWriteGenerator.generateReader(MapReadWriteGenerator.java:91)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcelExpression(ParcelableGenerator.java:282)
	at org.parceler.internal.ParcelableGenerator.buildReadFromParcel(ParcelableGenerator.java:234)
	at org.parceler.internal.ParcelableGenerator.buildParcelRead(ParcelableGenerator.java:166)
	at org.parceler.internal.ParcelableGenerator.generateParcelable(ParcelableGenerator.java:100)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:54)
	at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:34)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
	at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.parceler.transfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
	at org.parceler.transfuse.transaction.Transaction.run(Transaction.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Error:Execution failed for task ':app:compileDebugJava'.
> org.parceler.transfuse.TransfuseAnalysisException: @Parcel code generation did not complete successfully.
```
How does annotation should be changed to achieve its normal working state?
```java
@Parcel
public class RetroClientModel {

     @ParcelProperty("id")
     long id;

     @ParcelProperty("login")
     String login;

     @ParcelProperty("password")
     String password;
   ...
}
```
Is it necessary to use `ParcelFactory` each time to create Object instance as it was described in example?

**Comment by johncarl81** [comment]
Seems to build fine for me.  Are there any other non-built-in-types referenced in `RetroClientModel`?

**Comment by evasyuk** [comment]
@johncarl81, sorry - it is all my fault. I've missed that there was a HashMap object field. I thought that it would stay as NULL.

**Comment by rakesh-3607** [comment]
@evasyuk I am facing the same problem.

 @SerializedName("current_page")
        private String currentPage;
        @SerializedName("maximum_page")
  @SerializedName("search_result")
        private List<SearchResult> ewbSearchResult = new ArrayList<SearchResult>();


Would you please help me w, how to resolve this issue. I am using Retrofit with parcel.

**Comment by johncarl81** [comment]
@rakesh-3607, most likely your problem stems from the fact that you didn't declare the generic parameters on your `List`.  Is there some type that is always stored in this list?

**Comment by rakesh-3607** [comment]
Hi,

It's resolved. There was problem with inner class declared withing the main class that parse API response

Thanks

**Comment by rakesh-3607** [comment]
@johncarl81  Thanks
